### ISSUE TITLE
Disable individual Fault Tolerance annotation using external config

### ISSUE THREAD

**Issue by jGauravGupta** [eclipse/microprofile-fault-tolerance#109]
Based on the current state of Fault Tolerance configuration, It is not possible to disable specific annotation individually or globally. 

Possible solution could be :

1. Introduce an enabled element with default value true in annotation to disable it using external config source.
e.g : `com.acme.test.MyClient/serviceA/CircuitBreaker/enabled=false`
2. The annotation can be disabled via system properties in the naming convention of `<classname>/<methodname>/<annotation>=false`
e.g : `com.acme.test.MyClient/serviceA/CircuitBreaker=false`

**Comment by Emily-Jiang** [comment]
We can support this in the future release. At the moment, there is no urgent use case.

**Comment by johnament** [comment]
It looks like we already added support for this in 1.0.  Should the milestone be set?

**Comment by Emily-Jiang** [comment]
I updated this issue topic as it is kind of misleading. We do have support to disable all annotations except Fallback as this use case is required by Istio. What @jGauravGupta asks to disable individual annotation using separate configs. Since there is no definite use case as yet, we decide to defer to 1.1.

**Comment by Emily-Jiang** [comment]
@antoinesd will you be able to pick this one up?

**Comment by Emily-Jiang** [comment]
Let's use the name convention suggestion by @jGauravGupta 
disable on the class-level - this applies to all methods on the class
com.acme.test.MyClient/serviceA/CircuitBreaker/enabled=false
disable method-level: CircuitBreaker will be disabled on the method even if there is an class level annotation
com.acme.test.MyClient/serviceA/methodA/CircuitBreaker/enabled=false
disable globally: any method/class level CircuitBreaker is disabled
CircuitBreaker/enabled=false
