### ISSUE TITLE
CompletionStage return type support in Asynchronous

### ISSUE THREAD

**Issue by jGauravGupta** [eclipse/microprofile-fault-tolerance#110]
As mention in Asynchronous doc, The method annotated with Asynchronous must return a Future.
We should also consider to support `java.util.concurrent.CompletionStage`.

New Java EE 8 api like `javax.enterprise.event.Event.fireAsync(event)` in CDI 2.0 and JAX-RS 2.1 supports the `CompletionStage` return type.

**Comment by Emily-Jiang** [comment]
I had a further thought on this. Since the current javadoc says it must return a Future. CompleteableFuture is a Future and it has a CompletionStage. It should be fine. what do you think @jGauravGupta ?

**Comment by OndrejM** [comment]
I commented on [#35](https://github.com/eclipse/microprofile-fault-tolerance/issues/35#issuecomment-326897126) before I found this issue - I agree with @jGauravGupta, Async. should support `CompletionStage`. Supporting only `Future` feels very awkward and it's also blocking, there's no way around it.

We should aim for supporting `CompletionStage` in FT 1.1, and also define that the default executor for `...Async()` methods should have the correct security context or naming context associated with it, similar to the thread that handles the async processing.

**Comment by jGauravGupta** [comment]
It's ok @Emily-Jiang , we can target for `CompletionStage` interface support in the next release FT 1.1 .

**Comment by Emily-Jiang** [comment]
agreed @jGauravGupta @OndrejM ! We can get this done in FT 1.1.

**Comment by OndrejM** [comment]
Isn't this done with #267? Can we close this?

**Comment by Emily-Jiang** [comment]
strangely. A link should not trigger this issue to be reopened. I'll close this.
