### ISSUE TITLE
MP_Fault_Tolerance_NonFallback_Enabled uses non-standard naming conventions

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#125]
`MP_Fault_Tolerance_NonFallback_Enabled` uses non-standard `_` separators.  It should be using `.` separators

**Comment by Emily-Jiang** [comment]
. is not allowed to be contained in an environment variable name. Since this name is very usable to be set as an environment variable, hence the name. I don't quite understand why you say non-standard _ separator. What standard do you refer to?

**Comment by johnament** [comment]
Java properties are typically separated by `.` not `_`

I'm not sure what an environment variable has to do with this, since you're just asking your MP Config instance for the property value.  I know in GConfig we're translating `.` to `_` when looking for environment variables.

**Comment by Emily-Jiang** [comment]
I see what you meant. As for translating . to _, we did not define in Config API though. By the way, MP_Fault_Tolerance_NonFallback_Enabled is one property. I did not consider _ as separator. _ is a valid character to be used as part of system property. I think the confusion is that I did not mean _ as a separator but as part of the variable name.

**Comment by Emily-Jiang** [comment]
@johnament are you ok with my comments above?

**Comment by Emily-Jiang** [comment]
I plan to close this tomorrow if you don't have any objections.
