### ISSUE TITLE
Bulkheads should only apply to components that can be accessed from multiple contexts

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#126]
The bulkhead section does not mention that bulkheads only apply to components that can be access from multiple contexts.  It should be impossible to apply a bulkhead to a `@RequestScoped` bean, for instance.

**Comment by Emily-Jiang** [comment]
It is kind of no-op for RequestScoped bean. This may not be true in CDI-2.0 as the RequestScoped can be activated and we can do more for this bean. Therefore, I am kind of reluctance to add restriction here.

**Comment by hutchig** [comment]
What would be the advantage of this extra check?

**Comment by johnament** [comment]
@Emily-Jiang I'm not sure what this has to do with CDI 2.0.  Even when you activate request context, its once per thread.  You can't activate multiple request contexts on the same thread.

@hutchig the benefit is to help application developers understand why their bulkheads aren't working the way they expect.  If we clarify this behavior, they'll understand their bulkheads should be implicitly application scoped, or possibly session scoped.

**Comment by hutchig** [comment]
If we are clear that the bulkheads work per bean instance ('scope' as defined by CDI) then that is clear and applicable to all scopes. I think we should try to encapsulate the relationship between CDI scopes and threads in the CDI spec and not make further statements in the MP FT spec - even though many of the people involved overlap and are very knowledgeable about CDI.

**Comment by Emily-Jiang** [comment]
I am kind of agree with @hutchig ! John, I was not clear on CDI-2.0. Anyway, I was on something else. Back to your question, it is ok to start a new thread in a RequestScoped bean though. Do you agree?

**Comment by johnament** [comment]
@hutchig I disagree.  We actually aimed in the CDI 2.0 release to decouple threading and context activation.

**Comment by Emily-Jiang** [comment]
Back to your original question, John. It is ok to start a new thread in a request scoped bean by annotate the RequestScoped bean with async. For instance, a requested scoped bean is injected to a servlet, the servlet can invoke the same RequestScoped bean method. It is ok for a different thread to do the work in the RequestScoped bean. There is nothing wrong even though there is no performance gain. Therefore, I don't think we should limit it as there won't cause any issues.
I can add some wording in the spec to emphasize the real advantage of using bulkhead is mainly for resources accessible via multiple contexts.
