### ISSUE TITLE
Does configuration require the annotation to be present on a method?

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#127]
if a retry annotation is not present on a method, but I configure the method to have retry, etc configured, does that configuration still apply?

**Comment by Emily-Jiang** [comment]
yes, you need to configure it using the name convention className/method/Annotation/annotation_parameter.

**Comment by Emily-Jiang** [comment]
John, no annotation no FT. If a retry annotation is not presentation, any configuration on the method will be ignored.

**Comment by johnament** [comment]
Can you please propose adding this to the spec? Your two comments are contradictory, so its not clear which is right.

**Comment by Emily-Jiang** [comment]
sorry. My first response was misleading. When I said yes, it is yes to the issue question not the comment directly. I'll use this issue to clarify the spec.
