### ISSUE TITLE
Create timeout annotation

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-fault-tolerance#13]

**Comment by mkouba** [comment]
I think the `TimeOut` annotation would be easier to read/use if you rename:
* the annotation to `Timeout`
* `TimeOut.timeOut()` to `TimeOut.value()`
* `TimeOut.timeOutUnit()` to `TimeOut.unit()`

E.g. 
```java
@Timeout(500) // 500 ms
void foo() { }
@Timeout(value=5, unit=ChronoUnit.SECONDS) // 5 seconds
void bar() { }
```

**Comment by kenfinnigan** [comment]
+1

**Comment by Emily-Jiang** [comment]
@mkouba sounds good. Please provide a PR.
