### ISSUE TITLE
Is CircuitBreakerClientWithRetry.serviceC implicitly async?

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#131]
I'm looking at the definition of this class

```java
    @CircuitBreaker(successThreshold = 2, requestVolumeThreshold = 4, failureRatio = 0.75, delay = 50000)
    @Retry(retryOn = {RuntimeException.class, TimeoutException.class}, maxRetries = 7)
    @Timeout(500)
```

IT seems like the addition of timeout makes this invocation asynchronous.  However, it's a request scoped bean which can't be async.

**Comment by Emily-Jiang** [comment]
The Timout won't make it async. It is implementation details. One implementation is to use a different thread just to watch the time.

**Comment by johnament** [comment]
Ok, I think I see the issue.
