### ISSUE TITLE
force open a circuit breaker at runtime

### ISSUE THREAD

**Issue by jGauravGupta** [eclipse/microprofile-fault-tolerance#133]
**UseCase :**
In case of failure of service in production environment, Product team should be able to force open the circuit breaker at runtime using external config without the need for restarting the application.

**Force open :**
A new property circuitBreaker.forceOpen can be introduced, if true, forces the circuit breaker into an open (tripped) state in which it will reject/fallback all requests.

**At Runtime :** 
MP Config (dynamic configuration functionality) will also help to achieve this at runtime.

**Comment by Emily-Jiang** [comment]
We can discuss more after FT 1.0 release.

**Comment by Emily-Jiang** [comment]
This is useful. 

com.acme.MyClient/invokeService/CircuitBreaker/forceOpen = true;
only opens the circuit for the invokeService of com.acme.MyClient 
package com.acme;
public class MyClient{
   @CircuitBreaker
   public void invokeService() {

}
}

CircuitBreaker/forceOpen =true; globally open every circuit in the app.

**Comment by Emily-Jiang** [comment]
I have not seen a user request on this. Close for now.
