### ISSUE TITLE
Add a maxDuration to the Retry in CircuitbreakerRetryTest

### ISSUE THREAD

**Issue by neilgsyoung** [eclipse/microprofile-fault-tolerance#141]
The Service that is called in testCircuitOpenWithMultiTimeouts will time out a number of times (one for each retry) before the Circuit is opened. We should add a maxDuration to the @Retry to ensure that all the timeouts will be completed before the circuit is opened.

**Comment by Emily-Jiang** [comment]
thanks @neilgsyoung !
