### ISSUE TITLE
Increase the default maxDuaration to 5mins

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-fault-tolerance#144]
The current default value for Retry's maxDuration is 2seconds. According to some feedback from tests, it appears the value is too short. I suggest to increase it to be 5 mins. Thoughts?

**Comment by jGauravGupta** [comment]
I guess, you mean to increase it to be 5 seconds not min.

**Comment by Emily-Jiang** [comment]
I meant to be 5 mins, a longer time. I am fine with the current value if you all think it is good. @johnament @antoinesd what do you think? We need to finalise this today.

**Comment by johnament** [comment]
If you're making a REST call, where the HTTP service has a 60 second timeout (pretty common), then I agree that 2 seconds is not long enough.  Most of the time, you want this wrapper for external API calls.

**Comment by Emily-Jiang** [comment]
Thanks @johnament ! Let's use the common 60s as well then. Thank you @jGauravGupta for your comments! A pr to follow.

**Comment by johnament** [comment]
This needs further review, I believe just blindly merged something without thinking about it.

In `@Timeout` we specify how long the operation should run for.  When you combine this with `@Retry` I would assume that the `@Timeout` is applied to each attempt, not a cumulative value.  Therefore, the value of max duration makes more sense to be maxRetries * timeout value.  If timeout is not set, then its not an issue.

**Comment by Emily-Jiang** [comment]
maxRetries is the maximum time spent on the whole executions while time out is for per execution.

**Comment by Emily-Jiang** [comment]
It was not blindly merged by the way. I asked you to review. You had a question and I answered. You did not request for a change. I got Kevin to double check the issue and discussions.  By the way, you can still comment and we can do another change if needed. 

For your suggestion, unfortunately the default value is static. It's not a problem to set to a larger value, hence I suggested 5mins originally. If you suggest to set to 3mins, we can reset. After all, it is the default value, people should override it if they need to. Please let me know what you think.

**Comment by johnament** [comment]
I disagree about the merge part.  I asked a question, because I wasn't sure if I was reading it correctly or not.  You answered the question and then merged the change.

**Comment by Emily-Jiang** [comment]
I am sorry for my misunderstanding. I thought I did based on your comments. I got Kevin to review the changes. I should have waited instead of assuming it. I am so sorry. I did not close this issue and do plan to do any update if necessary. I'll send another PR shortly.
