### ISSUE TITLE
Create interceptors for JAX-RS client

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-fault-tolerance#15]
Some functionality would be nice to have in JAX-RS client instances, since JAX-RS is already in MP.
They could be registered for:
 - individual client instances with `client.register()` method
 - globally via an SPI we would need to define - either with a default config, or via a name which could be set with client.setProperty("MICROPROFILE_NAME", "my-client-name")

This would be useful for circuit breakers, retries, etc.

It would be also useful to define producers for client instances so that a JAX-RS client could be injected, with reasonable defaults configurable with fault-tolerance annotations:

```
@Inject @Retry @CircuitBreaker Client webClient;
```

Maybe we should create a new proposal for JAX-RS extensions and keep this functionality separate from the general Fault Tolerance proposal?

**Comment by kenfinnigan** [comment]
Like the ideas around this, just not sure whether it should be separate.

If it's relying on functionality that will be delivered by FT proposal, then it either needs to be done as part of that or a follow on proposal that depends on it

**Comment by Emily-Jiang** [comment]
Ondrej, we can discuss your suggestion in the next hangout.

**Comment by Emily-Jiang** [comment]
close this one as it was out of date and I don't think it is relevant any more.
