### ISSUE TITLE
RetryTimeoutTest seems to contradict spec

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#157]
`RetryTimeoutTest` seems to contradict the [retry.adoc](https://github.com/eclipse/microprofile-fault-tolerance/blob/master/spec/src/main/asciidoc/retry.asciidoc) spec.  Specifically, it indicates that the `TimeoutException` is what triggers the retry.  However, the comments in the test indicate that a `TimeoutException` is expected.

If a `TimeoutException` is expected, that can only mean that upon failure, a retry will throw the underlying exception that caused it to fail.  This behavior is not specified though.

**Comment by Emily-Jiang** [comment]
The TimeoutException will trigger retry if it meets the retryOn condition. After the maximum retries were performed, the exception will pass back to the client. I'll improve the spec to clarify this.

**Comment by Emily-Jiang** [comment]
I think #176 should clarify this.

**Comment by Emily-Jiang** [comment]
Please let me know if you think otherwise.
