### ISSUE TITLE
CircuitBreakerClientWithRetry has confusing retryOn values

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#159]
This retry on does make much sense: `@Retry(retryOn = {RuntimeException.class, TimeoutException.class}, maxRetries = 7, maxDuration = 20000)`

`TimeoutException` extends from `RuntimeException`, and the spec seems to indicate we always have to treat `TimeoutException` as a retry so this seems contradictory

**Comment by Emily-Jiang** [comment]
That is not what the spec tries to mandate. The spec just says one example. We can reword the spec to clarify the ambiguity.
