### ISSUE TITLE
Is MP_Fault_Tolerance_NonFallback_Enabled intended to be dynamic or static?

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#172]
MP Config indicates that configuration values are evaluated on each execution, its up to the underlying config source whether or not the value is dynamic or static.

For a property like `MP_Fault_Tolerance_NonFallback_Enabled` it's not clear if this should be evaluated on bootstrap or when evaluating the actual execution.  The test seems to prefer on bootstrap, by using a static property.  Is that the intention here?  Should impls only need to support on bootstrap of this setting?

**Comment by Emily-Jiang** [comment]
As per the spec, 
In order to prevent from any unexpected behaviours, the property
MP_Fault_Tolerance_NonFallback_Enabled will only be read on application starting. Any dynamic
changes afterwards will be ignored until the application restarting.

**Comment by Emily-Jiang** [comment]
close this one as I have replied the question.
