### ISSUE TITLE
How to differentiate config for same method name

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#173]
Given I have the following API signature:

```java
package org.eclipse.microprofile.ft.samples;

public class SampleBean {
   @Retry
   public String doWork(String arg) {
    //...
   }
   @Retry
   public String doWork(String arg, int count) {
    //...
   }
}
```

How would I differentiate the config for these two methods?  Both seem like they would point to the same properties, and when you configure one via properties the other automatically gets those same properties set.

**Comment by Emily-Jiang** [comment]
It was viewed the overloading method would use the same configuration as the effort of decaffeinating them will make the configuration unreadable. The workaround is to use a different method name if different configuration is needed.

**Comment by Emily-Jiang** [comment]
@johnament please see my comments above. Are you ok for this issue to be closed? I'll close it tomorrow if no objections.
