### ISSUE TITLE
Wrong exceptions used in TCK

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#174]
In the various javadocs for fault tolerance, configuration issues are defined by `FaultToleranceDefinitionException`.  However, the TCK in multiple places expects `javax.enterprise.inject.spi.DefinitionException` to be thrown.

The two exceptions are not compatible with one another, the fault tolerance exception does not extend the CDI one.  

Either, `FaultToleranceDefinitionException` extends `DefinitionException` or the TCK needs to be updated to reflect the proper exception being thrown.

**Comment by Emily-Jiang** [comment]
will update TCK to fine tune this. Since the implementation is to use CDI, All validation exception will eventually wrap under `javax.enterprise.inject.spi.DefinitionException.`

**Comment by johnament** [comment]
I just took a look at how Weld is using `DefinitionException`, under no situation is it being thrown as a part of a deployment validation problem, so I believe the only valid outcome is to look for `DeploymentException`.  You can see how we're doing this properly in the config project - [MissingValueOnInstanceInjectionTest.java#L40](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/broken/MissingValueOnInstanceInjectionTest.java#L40)

**Comment by Emily-Jiang** [comment]
@johnament On the call, we agreed the current tests are ok and the DefinitionException is the right. I'm going to close this one. Please let me know if you have any objections.

**Comment by smillidge** [comment]
The test should actually just catch Exception. We run our tests with a remote Arquillian Server profile and these tests assume an embedded profile.

**Comment by smillidge** [comment]
@johnament the config tests have the same problem they assume an embedded profile.

**Comment by Emily-Jiang** [comment]
I believe this issue has been solved via the hangout and the new version of the Arquilliant upgrade.
