### ISSUE TITLE
Fallback Spec Inconsistency

### ISSUE THREAD

**Issue by Pandrex247** [eclipse/microprofile-fault-tolerance#177]
The specification document for the Fallback annotation (https://github.com/eclipse/microprofile-fault-tolerance/blob/master/spec/src/main/asciidoc/fallback.asciidoc) states that the annotation can be applied to a method or a class. The annotation however only has a target value type of _Method_, the option to have it put on a class being removed in https://github.com/eclipse/microprofile-fault-tolerance/issues/111.

I assume it's the spec that hasn't been updated to reflect the change? Or is it the other way around?

**Comment by Emily-Jiang** [comment]
@Pandrex247 thanks for reporting this. Yes, the spec was not updated to reflect the change. Please submit a PR.
