### ISSUE TITLE
Most Bulkhead tests use invalid CDI beans

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#179]
Most of the bulkhead tests are using invalid CDI beans.  Here are some examples:

- [Bulkhead55ClassAsynchronousRetry1Bean](https://github.com/eclipse/microprofile-fault-tolerance/blob/master/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Bulkhead55ClassAsynchronousRetry1Bean.java)
- [BulkheadMethodAsynchronousDefaultBean](https://github.com/eclipse/microprofile-fault-tolerance/blob/master/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodAsynchronousDefaultBean.java)

Where as there are other valid beans:

- [Bulkhead55ClassSynchronousRetryBean](https://github.com/eclipse/microprofile-fault-tolerance/blob/master/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Bulkhead55ClassSynchronousRetryBean.java)

The problem is that the tests use an empty `beans.xml` file, which works differently in CDI SE and Java EE.  In Java EE these are valid beans because of the default discovery behavior.  However, its not required to work in SE mode.  

Ideally, each of these test clients would have a scope applied to them to make them discovered.

**Comment by Emily-Jiang** [comment]
John, feel free to improve the tests with a scope so that the tests can run on both EE and SE environment.

**Comment by Emily-Jiang** [comment]
Carlos, please take a look at this ticket.

**Comment by carlosdlr** [comment]
ok, i'll check @Emily-Jiang

**Comment by carlosdlr** [comment]
Hello, @Emily-Jiang 

I already made the change related to the @johnament comments regarding the CDI injection.

Please check and let me know if is something else needed.

Thank you
