### ISSUE TITLE
Add ElementType.TYPE to annotations @Target

### ISSUE THREAD

**Issue by antoinesd** [eclipse/microprofile-fault-tolerance#18]
Not having these prevents creation of CDI interceptors in implementations.

**Comment by Emily-Jiang** [comment]
Are we try to allow these annotations on the class level? Is this useful?

**Comment by antoinesd** [comment]
Yes because if you want to declare a CDI interceptor you have to add these annotations as InterceptorBinding on the interceptor class. Missing `Type` in target prevent this.
