### ISSUE TITLE
Unclear on behavior of iteration count

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#180]
I'm trying to debug my way through this test -> [BulkheadAsynchRetryTest.java#L165](https://github.com/eclipse/microprofile-fault-tolerance/blob/master/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadAsynchRetryTest.java#L165)

What strikes me is that it launches 1000 iterations, seemingly for unknown reasons, to verify that a `BulkheadException` is thrown.

I don't understand this test at all unfortunately.

At what point are you expecting the BHE to be thrown?  I don't see anything about this test that would be triggering a BHE.

**Comment by hutchig** [comment]
I wrote this test and will have a look. Apologies if it is causing a problem.

**Comment by hutchig** [comment]
1000  is just a number that is obviously 'too many' for the bulkhead * the retries. 
So we have a loop attempting to firing 1000 things into an asych bulkhead of size 5 and waitingTaskQue 5 and maxRetries of 10. 
```
for (int i = 0; i < 1000; i++) {
                results[i] =  BulkheadRapidRetry55MethodAsynchBean::test(new Checker(1 * 1000, td));
            }

public class BulkheadRapidRetry55MethodAsynchBean implements BulkheadTestBackend {
    @Override
    @Bulkhead(waitingTaskQueue = 5, value = 5)
    @Asynchronous
    @Retry(retryOn =
    { BulkheadException.class }, delay = 1, delayUnit = ChronoUnit.MICROS, maxRetries = 10, maxDuration=999999)
    public Future test(BackendTestDelegate action) throws InterruptedException {
        Utils.log("in business method of bean " + this.getClass().getName());
        return action.perform();
    }
```
The queue will fill up and throw a bulkhead exception, this will be retried 10 times, to again fail, rinse and repeat until the bulkhead exception percolates back to the client on 'RetryOverload'. 
Hence the name of the test "testBulkheadMethodAsynchronous55RetryOverload". 

Have you a reasoning on how the test is incorrect? (Happy to learn if I am wrong as I can't see the error currently.)

**Comment by hutchig** [comment]
So to be clear, the client bulkhead exception will occur on the 11th time (maxRetries+1) that a task is resubmitted while both the bulkhead and queue are full - note that quite a few tasks will be able to get into the queue on the 2nd, 3rd,,,10th. attempt and once there will not get a bulkhead exception. How many this is depends on how fast the tasks get created (which varies by machine a little) racing how fast they get through the bulkhead (which varies by machine a little) that is why I set the loop to 1000.

**Comment by johnament** [comment]
@hutchig  you're the first to say the test is incorrect, I did not say that.  My point is that the test is unclear in what it's trying to verify, and there is no corresponding spec for this behavior.  Likewise, since bulkheads are meant for concurrent access, using a single thread to generate load need not necessarily work.

**Comment by hutchig** [comment]
Well the test is called 
  testBulkheadMethodAsynchronous55RetryOverload
A bulkhead test, with method annotation, for an asynchronous bulkhead, 
55 is the size of the bulkhead (5) and queue (5) and it is trying to verify retry
overload!

I know the comment is short at
   * Tests overloading the Retries by firing lots of work at a full Method bulkhead
but you are welcome to improve it :-) .

I had you in mind (or at least Hammock) when wondering how to create asynch
workloads in the tests.  For JEE I would have created threads one way and for JSE
another - in the end I used the @Annotation itself. 

I agree that the nesting/precedence order of the different annotations could be
specced more clearly (at least when I last looked).

**Comment by johnament** [comment]
We had faced a similar concern with the JWT spec earlier, @starksm64 had introduced an SPI that would allow you to parse a JWT per impl.  It was ultimately deemed unneeded.  Maybe that approach would have worked here, to be able to give out a `Scheduler` or an `ExecutorService` to be able to generate threads.

Also, please note that the actual FT impl is Apache Safeguard.  I plan to get tests working for Safeguard on TomEE in addition to CDI SE mode.  This way it can actually be tested on at least a Web Profile container.

**Comment by Emily-Jiang** [comment]
In JavaEE environment, the app server will supply executor themselves so that some of the contexts can be propagated. You are free to choose in JavaSE but the api does not need to know anything about this.

**Comment by Emily-Jiang** [comment]
@johnament are you happy with the comments? Do you still want to keep this ticket open? Or I can close it and you reopen it if you see any problems when you have chance to try on TomEE?

**Comment by Emily-Jiang** [comment]
close this issue for now. Please reopen if you see any problem occurring.
