### ISSUE TITLE
What attributes are meant to be configurable?

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#181]
The spec leaves this ambiguous, and since the TCK makes most of the assertions it's not clear what is correct.

The TCK only checks for these properties:

```
org.eclipse.microprofile.fault.tolerance.tck.config.clientserver.ConfigClient/serviceA/Retry/maxRetries=3
org.eclipse.microprofile.fault.tolerance.tck.config.clientserver.ConfigClassLevelClient/Retry/maxRetries=3
org.eclipse.microprofile.fault.tolerance.tck.config.clientserver.ConfigClient/serviceC/Retry/maxDuration=1000
org.eclipse.microprofile.fault.tolerance.tck.config.clientserver.ConfigClassLevelMaxDurationClient/Retry/maxDuration=1000
```
Based on this, I can only assume that only `maxRetries`  and `maxDuration` are configurable.

**Comment by Emily-Jiang** [comment]
You were right that TCK did not cover all of them. All of the attributes are configurable. Feel free to submit a PR.

**Comment by johnament** [comment]
Unfortunately, it's more complicated than that.

How does one configure a `ChronoUnit`?  The spec mentions `100ms`, which implies the amount and unit are configured as one value.  However they're two values.  Assuming we are configuring the unit separately, do we use the `name` attribute or the actual object?

Likewise, for exceptions to consider, is it a fully qualified class name? or a short name?  Is the array comma separated? colon?

**Comment by Emily-Jiang** [comment]
ChronoUnit is to configure whether ChronoUnit.MILLIS or ChronoUnit.HOURS etc. What 100ms do you mean? These will have two fields joined together. If the delay is 100ms, you configure delay with 100 and delayUnit with ChronUnit.MILLIS.

**Comment by johnament** [comment]
https://github.com/eclipse/microprofile-fault-tolerance/blame/0e563940ded43911941e0aa6c83582ce10615ee6/spec/src/main/asciidoc/configuration.asciidoc#L60 mentions `100ms` explicitly as configurable.

**Comment by johnament** [comment]
Can you give an example of what this configuration looks like in MP Config, as you understand it?  E.g. what does the properties file look like?

**Comment by Emily-Jiang** [comment]
```
package com.acme.ft
public class MyTimeout{

@Timeout(100)
public void doSomething() {

...
}

}
```
In order to config this timeout to 300ms
set two config properties;
com.acme.ft.MyTimeout/doSomething/Timeout/value=300
com.acme.ft.MyTimeout/doSomething/Timeout/unit=ChronoUnit.MILLIS

**Comment by Emily-Jiang** [comment]
@johnament are you still have question on this? If no, I plan to close this.
