### ISSUE TITLE
Add more configuration based TCK tests

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#182]
The following behaviors are not tested:

- Having a property set for both the method and the class
- Having a property set in a global fashion that overrides the other class/method annotations
- Property configuration for global
- Bulkhead configuration
- CircuitBreaker configuration
- Timeout configuration
- Exception class conversion (should this be moved to the config spec?)
- TimeUnit conversion (should this be moved to the config spec?)

**Comment by Emily-Jiang** [comment]
Thanks for reporting this @johnament ! Feel free to submit PR if you get to it first.

**Comment by Emily-Jiang** [comment]
@antoinesd can you help with this?

**Comment by antoinesd** [comment]
yes @Emily-Jiang

**Comment by antoinesd** [comment]
Added PR. Test related to converters should be added to config IMO
