### ISSUE TITLE
Clarify whether method uses declaring class or current class

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#183]
Suppose I have the following:

```java
public class ServiceA {
    @Retry
    public String doIt() { .. }
}
public class ServiceB extends ServiceA {
    @Retry
    public String again() { .. }
}
public class ServiceC extends ServiceA {
     @Override
     public String doIt() { .. }
}
```

Given that these are all fault tolerant methods, and I'm using instances of `ServiceB` and `ServiceC`, what configuration should be used for the method `doIt` in these cases?  Do I use `ServiceA` as the configuration key or the actual impls?

**Comment by Emily-Jiang** [comment]
For ServiceB instance, doIt() is from serviceA, which has retry.. For ServiceC instance, doIt is from ServiceC, which has no retry.

**Comment by McFoggy** [comment]
And if we have
````java
@Retry
public class ServiceD extends ServiceA {
}
````

Which configuration of `@Retry` has to be used when method `doIt()` is called on an instance of ServiceD?
1. the one from ServiceD class 
2. or the one from original method ServiceA

I would hope (1) is expected, is that right?

**Comment by McFoggy** [comment]
Sure, I will.

**Comment by Emily-Jiang** [comment]
@McFoggy @johnament please read my PR to see whether it is clearer.

**Comment by johnament** [comment]
@Emily-Jiang if you assign reviewers to a PR it'll show up in inboxes.  Which PR are you referring to?

**Comment by McFoggy** [comment]
@johnament I guess it is #195 which relates to this issue
