### ISSUE TITLE
CircuitBreakerTest#testCircuitClosedThenOpen should have a configurable delay period

### ISSUE THREAD

**Issue by starksm64** [eclipse/microprofile-fault-tolerance#184]
When looking at the circuit breaker related TCK tests, I'm seeing that the CircuitBreakerTest#testCircuitClosedThenOpen runs in a tight loop and expects that the state of the circuit follows in a synchronous fashion.

This prevents use of a statistical type of circuit breaker implementation like HystrixCircuitBreakerImpl, which monitors the various invocation stats in a background thread with a periodic rate that has a minimum resolution of 1ms. Even at this resolution, all 7 of theclientForCBWithDelay invocations are complete before the circuit state is even checked once.

It seems like there should be a configurable delay between the theclientForCBWithDelay invocations that would allow for background tracking of a circuit.

If there is supposed to be hard requirement that a circuit breaker track the invocations of a method synchronously, then that should be clarified in the spec and an option to relax this should be added to the @CircuitBreaker as this does not seem practical for scalability.

**Comment by Emily-Jiang** [comment]
Scott, the delay in the CircuitBreaker annotation is to confirm the delay to check the circuit status. You can configure it. Do you mean the tests should have set a longer delay period? At the moment, the delay is 5s to check the circuit status after it is open.

**Comment by Emily-Jiang** [comment]
@antoinesd are you going to propose a PR?

**Comment by Emily-Jiang** [comment]
close this as the dup was fixed.
