### ISSUE TITLE
Clarify usage of Timeout with Asynchronous and cover it by tests

### ISSUE THREAD

**Issue by OndrejM** [eclipse/microprofile-fault-tolerance#185]
The specification mentions that `@Timeout` can be used with `@Asynchronous`, but doesn't explain how it should behave and it's also not covered by tests.

I propose that if both are used and timeout happens, the specification should mandate that the future is canceled at the time the execution takes longer than timeout, not after execution is finished. It would also mean that probably a background thread would need to monitor all async timeout calls and check if they take longer than timeout but that's implementation detail. If `future.get` is called, then it should throw `TimeoutException` at the time when a timeout occurs, not when the execution is finished.

This is to notify the caller of a timeout immediately and prevent delays in case the asynchronous task is waiting on a blocking call.

This should also be covered by tests. Currently, tests only cover using `@Retry` without any other annotations.

**Comment by Emily-Jiang** [comment]
Ondrej,

The spec has the following `[claim ](http://microprofile.io/project/eclipse/microprofile-fault-tolerance/spec/src/main/asciidoc/timeout.asciidoc)`


When @Timeout is used without @Asynchronous, the current thread will be interrupted with a call to Thread.interrupt() on reaching the specified timeout duration. The interruption will only work in certain scenarios. The interruption will not work for the following situations:

    The thread is blocked on blocking I/O (database, file read/write), an exception is thrown only in case of waiting for a NIO channel

    The thread isn’t waiting (CPU intensive task) and isn’t checking for being interrupted

    The thread will catch the interrupted exception (with a general catch block) and will just continue processing, ignoring the interrupt

In the above situations, it is impossible to suspend the execution. The execution thread will finish its process. If the execution takes longer than the specified timeout, the TimeoutException will be thrown and the execution result will be discarded.
Is it still unclear? I agree a separate test should be added to test this.

**Comment by Emily-Jiang** [comment]
close this one as tck and spec are updated.
