### ISSUE TITLE
Clarification on CircuitBreaker failureRatio & requestVolumeThreshold

### ISSUE THREAD

**Issue by McFoggy** [eclipse/microprofile-fault-tolerance#188]
By implementing the spec in a [portable JEE7 compliant way](https://github.com/McFoggy/portable-mpft-jee) I am puzzling with some CircuitBreaker tests & CircuitBreaker javadoc.

The javadoc looks quite clear to me, I read it like the following:
- _requestVolumeThreshold_: the size of a window of consecutive calls to take into account
- _failureRatio_: a percentage of failures within a window that trigger the circuit to open

But if we look at [CircuitBreaker#testCircuitDefaultSuccessThreshold](https://github.com/eclipse/microprofile-fault-tolerance/blob/1.0/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerTest.java#L182), we see that this test defines a window of 4 consecutive calls for which 3 of them are expected to open the circuit (0.75 ratio).

If we look at the test & expected calls, starting from step 6, calls are: `SFFFFC`  (S: succesful call, F: failed call, C: call).
The TestNG test expects the circuit to open only after the 4th failed call _(ie after failed call 10)_.  
But if we consider the sliding window of 4 consecutive calls, then after the sequence `SFFF` _(ie after failed call 9)_, the 0.75 failure ratio is hit and should open the circuit.

If we really respect the tck tests, then for the same service as the one used in the above test sequences like `FFFSFFFSFFFS` which are constantly at 0.75 error rate never open the circuit.

Should we change the test to fail at step 9?

**Comment by McFoggy** [comment]
Also the interpretation of `requestVolumeThreshold()` has to be clarified.

Do we have (1) to wait for a minimum amount of `requestVolumeThreshold()` calls before starting evaluating circuit state, or (2) shall we do our best to fail asap.

- If it is (1), then the beginning of [CircuitBreakerTest#testCircuitDefaultSuccessThreshold](https://github.com/eclipse/microprofile-fault-tolerance/blob/1.0/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerTest.java#L182) and [CircuitBreakerTest#testCircuitHighSuccessThreshold](https://github.com/eclipse/microprofile-fault-tolerance/blob/1.0/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerTest.java#L246) is correct arguing that evaluation starts only after having `requestVolumeThreshold()` calls in the window. This behavior looks to be the one expected by the current TCK.
- if (2) then several tests inlcuding but not limited to [CircuitBreakerTest#testCircuitDefaultSuccessThreshold](https://github.com/eclipse/microprofile-fault-tolerance/blob/1.0/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerTest.java#L182) and [CircuitBreakerTest#testCircuitHighSuccessThreshold](https://github.com/eclipse/microprofile-fault-tolerance/blob/1.0/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerTest.java#L246) should have the first CircuitBreakerOpenException to  be raised earlier at step 4.

**Comment by Emily-Jiang** [comment]
The expectation is "wait for a minimum amount of requestVolumeThreshold() calls before starting evaluating circuit state". I will clarify this in the spec.
