### ISSUE TITLE
Asynchronous Enhancement - String property to indicate thread pool

### ISSUE THREAD

**Issue by smillidge** [eclipse/microprofile-fault-tolerance#189]
As an enhancement request can we add an opaque string property to Asynchronous which can be used to indicate to an implementation which thread factory, thread pool/Managed Executor or whatever to use to get a thread?

From a spec point of view an implementation could be free to ignore the property or use it to segregate requests. This can be important when tuning large throughput systems

**Comment by Emily-Jiang** [comment]
Steve, do you mean the application developer mandates the runtime which way to create a thread? I guess I don't quite get what you meant. Does the developer needs to know which way to get the thread? If the implementation is free to ignore this info, what is the use of the property?

**Comment by smillidge** [comment]
Something like;
```java
@Asynchronous(threadPool="service-pool")
public void foo() {
}
```
That way depending on the capabilities of the Microprofile runtime the developer could configure a specific thread pool with the name "service-pool". For example in Payara Server they could create a Thread Pool and all Asynch threads for the method foo would execute on that thread pool.

If the same application was then deployed onto a runtime that does not support configurable thread pools then there would be no effect.

**Comment by Emily-Jiang** [comment]
@McFoggy @antoinesd and I discussed this today. Broadly speaking, we will explore this idea in the future release.

**Comment by Emily-Jiang** [comment]
We discussed this once more today. We think it is implementation specific details. It might be good for the implementation to extend the MP FT to support this extra functionality in particular application servers. We think the portability is key to MP specs. If the app behaves different in different runtimes that implement the MP FT, the behaviour is not desirable. Will close this issue for now.
