### ISSUE TITLE
make code style compliant with defined rules

### ISSUE THREAD

**Issue by McFoggy** [eclipse/microprofile-fault-tolerance#190]
today by editing code in Intellij, `.editorconfig` is used.  
Especially the following rules:
````
trim_trailing_whitespace = true
insert_final_newline = true
````
are not respected by the current code base.

This makes any code change a mess not to pollute the commit with unrelated spaces changes.

There should be an alignement between the different "code style checks" provided with the project, either:
- checkstyle is adapted to respect the rules and rules are applied to all files
- no `.editorconfig` is provided or should be used unless [editorconfig#208](https://github.com/editorconfig/editorconfig/issues/208) is clarified.

For the moment I'll disable my editor config compliancy in Intellij.

**Comment by Emily-Jiang** [comment]
@carlos please take a look.

**Comment by carlosdlr** [comment]
s
