### ISSUE TITLE
TCK is missing tests for standalone Asynchronous

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-fault-tolerance#194]
See also https://github.com/eclipse/microprofile-fault-tolerance/blob/master/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsynchronousInvocation.java

The TCK also misses a test that `FaultToleranceDefinitionException` is thrown if a method annotated with `@Asynchronous` does not return `Future`.

**Comment by johnament** [comment]
Is it supposed to be a constraint?  I honestly had no idea.

**Comment by antoinesd** [comment]
In section 4.1, the spec states:

> The method annotated with `@Asynchronous` must return a Future, otherwise, `FaultToleranceDefinitionException` occurs

So it looks like a constraint.

**Comment by johnament** [comment]
But I can also apply `@Asynchronous` to a class.  I can also add `@Bulkhead` to the mix and then what's expected?

**Comment by mkouba** [comment]
I would guess `@Asynchronous` declared on a class => all methods must return `Future`.

**Comment by antoinesd** [comment]
+1

**Comment by Emily-Jiang** [comment]
yes @mkouba !

**Comment by Emily-Jiang** [comment]
please feel free to do a PR to add tests @mkouba !

**Comment by Emily-Jiang** [comment]
@antoinesd @mkouba pls help with adding more tests.

**Comment by antoinesd** [comment]
Taking it

**Comment by arjantijms** [comment]
Just a though, but wouldn't a standalone @Asynchronous annotation more belong in a concurrency spec?
