### ISSUE TITLE
TCK assumes a circuit breaker transitions to a new state when a fault tolerance operation completes

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-fault-tolerance#196]
This assumption prevents from leveraging libraries such as Hystrix. For example in Hystrix a circuit breaker could transition from CLOSED to OPEN state only when a new "health snaphot" is taken (error percentages are calculated, see also [1]) and the state is set _asynchronously_ with respect to the thread invoking a fault tolerance operation.

Therefore, there should be a **configurable property** that would represent a **minimal delay** between two subsequent fault tolerance operations.

Note that a similar assumption makes no sense in most real scenarios.

[1]
https://github.com/Netflix/Hystrix/wiki/Configuration#metrics.healthSnapshot.intervalInMilliseconds

**Comment by mkouba** [comment]
This issue duplicates https://github.com/eclipse/microprofile-fault-tolerance/issues/184

**Comment by Emily-Jiang** [comment]
@mkouba can you do a PR to demonstrate how you think about improving the tck? thanks
