### ISSUE TITLE
allow tests using arquillian @ShouldThrowException to be processed by an ArchiveProcessor

### ISSUE THREAD

**Issue by McFoggy** [eclipse/microprofile-fault-tolerance#200]
due to https://issues.jboss.org/browse/ARQ-2143 tests using `@ShouldThrowException` are not processed by an ArchiveProcessor that the _implementor/implementation_ would have registered.
This makes implementations based on an enhancement of the test deployable (the test war) to not be added to the deployable under test ; making for sure the test to fail because of the absence of the implementation.

**Comment by Emily-Jiang** [comment]
The change looks good. @neilgsyoung is in the process of running against Open Liberty to make sure everything is ok and then merge in. thanks @McFoggy !
