### ISSUE TITLE
FT Annotation inheritance

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-fault-tolerance#204]
The current Fault Tolerance annotation annotations have @Inherited to follow the pattern done by other Java EE spec, e.g. @Transactional.  @McFoggy brought this up during FT hangout. For example,

  ```
@Retry
  public class MyBase {
 
       @Retry(maxRetries=5)
       public void invokeServiceA() {
           ...
        }
        public void invokeServiceC() {
            ...
        }
   }

   public class MySub extends MyBase{
 
         @Override
          public void invokeServiceA() {
              ...
           }

   }
```
In this scenario, MySub will inherit the retry annotation, which will apply to the method invokeServiceA(), even though invokeServiceA() has no FT annotation. It is hard to get rid of the Retry annotation for invokeServiceA() if needed. 

I would like to propose 2 options
1. Remove @Inherited from all FT annotations. It will be a behaviour change and it should not be too much a problem. The workaround is to add the annotation on the subclass.

2. Remove @Inherited from all FT annotations but add one method to say inherited with the default return value of false. The downside is that it clutters the api.

Personally I will vote option 1. 
Thoughts?

**Comment by McFoggy** [comment]
> In this scenario, MySub will inherit the retry annotation, which will apply to the method invokeServiceA()

from a Java point of view this is not true. `java.lang.annotation.Inherited` annotation does not bring you the visibility of the `@Retry` annotation on sub-classes methods.

I just pushed a test for this in #192, commit link is [31d90f86](https://github.com/eclipse/microprofile-fault-tolerance/pull/192/commits/31d90f864e7e7544a792e84890083f9c36a4605e)

**Comment by johnament** [comment]
It should be option 1.  Option 2 means we need to crawl the tree of classes, as well as introducing a non-standard behavior pattern.

**Comment by Emily-Jiang** [comment]
Thanks @johnament ! @McFoggy it is not JavaSE we are talking about. Since Retry is an interceptor binding, if you apply it on class level, all methods will inherit it.

**Comment by McFoggy** [comment]
@Emily-Jiang agree because of the Retry on the class. My latest example was defining Retry only at method level, sorry if I disturbed the discussion.

**Comment by Emily-Jiang** [comment]
no problem @McFoggy ! Thank you so much for demonstrating this!

**Comment by Emily-Jiang** [comment]
Close this one as @johnament mentioned later if we remove the `Inherited`, FT interceptor bindings will be anti-pattern. We settled the [issue ](https://github.com/eclipse/microprofile-fault-tolerance/issues/183), which was the cause for this issue to state that we config the properties on the declaring class. Spec has been updated to make the message clearer.
