### ISSUE TITLE
Specify that @javax.ejb.Asynchronous can be used instead of @Asynchronous in MP

### ISSUE THREAD

**Issue by OndrejM** [eclipse/microprofile-fault-tolerance#205]
Since `@javax.ejb.Asynchronous` is already specified in the EJB spec and many MP implementations already provide it, I suggest to specify that it can be used instead of `org.eclipse.microprofile.faulttolerance.Asynchronous` as an alternative. For many developers it could be confusing that there are 2 @Asynchronous annotations provided by an implementation and only one of them works. It's very easy to use the wrong one.

In terms of TCK, a test would be executed only if `@javax.ejb.Asynchronous` is on the classpath so that it passes or is ignored for implementations that don't provide it.

**Comment by kenfinnigan** [comment]
I'm -1 on this.

It's only an issue when those two annotations happen to be on the classpath, which is not the case with every MP implementation.

Also, it's no different than the situation with other annotations in Java EE that are re-used between specifications.

**Comment by Emily-Jiang** [comment]
-1. Besides what @kenfinnigan states above, I would not like to introduce the dependency on ejb api. Besides, we have better control on our async and we will be able to expand it. Everything with ejb on will send a false alarm being heavy.

**Comment by McFoggy** [comment]
-1 to integrate the spec.

But one could expect a JEE implementation of FT to handle it, why not. By doing so, your project will be non FT portable anymore but tied to any implementation that would support that.

**Comment by antoinesd** [comment]
-1 for me as well

**Comment by Emily-Jiang** [comment]
I'll close this issue as there are enough -1.

**Comment by carlosdlr** [comment]
-1 for me
