### ISSUE TITLE
git policy for the project

### ISSUE THREAD

**Issue by McFoggy** [eclipse/microprofile-fault-tolerance#206]
Wouldn't it be beneficial to define some rules regarding the management of git history:
- how to merge PR
  - rebase vs merge
  - squash non relevant commits
- long living branches merged several time
- ...

having some rules could:
- bring a clean & meaningful history
- provides rules for admins to ease (or at least guide) their management tasks when accepting PRs

**Comment by Emily-Jiang** [comment]
@McFoggy This is a good suggestion. please bring this up in the MicroProfile google group. The suggestion applies to all MP projects.

**Comment by McFoggy** [comment]
done under this thread: https://groups.google.com/forum/#!topic/microprofile/dObuz0VFiLw

**Comment by Emily-Jiang** [comment]
Let's carry on the discussion on MP google group. It is not directly related to this repo. Close it for now.
