### ISSUE TITLE
Need to update spec pom.xml for proper pdf and html generation

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile-fault-tolerance#212]
Just a gentle reminder that since this component has not used the updated release process yet, you will need updates to your spec's pom.xml file for proper generation of the pdf and html.  We found a couple of hiccups with components during the MP 1.3 release, so I'm creating a couple of Issues as reminders.  You can reference the Config component as an example of proper usage.

**Comment by carlosdlr** [comment]
This fix is already done in commit https://github.com/eclipse/microprofile-fault-tolerance/commit/5e98da3e24d4611154cb44bf18eb55dee523aedb by @Emily-Jiang

**Comment by kwsutter** [comment]
Resolved via PR #219.
