### ISSUE TITLE
Consistent *Unit setting names for Retry

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile-fault-tolerance#217]
As I was experimenting with Fault Tolerance, I was surprised by the inconsistent naming of the *Unit values with the @Retry annotation.

First off, delay and delayUnit is consistent and what I would expect.

But, we have maxDuration and durationUnit.  I would have expected maxDurationUnit.

And, then we have jitter and jitterDelayUnit.  This one is a bit trickier.  To be consistent, I would have expected just jitterUnit.  But, I can kind of understand the "delay" qualifier.  And, jitterDelay is not correct.  I would still suggest just using jitterUnit to be consistent.

This Issue is a nit, but iterating to improve the user experience is always good.

**Comment by Emily-Jiang** [comment]
We discuss this issue in today's hangout. We have two options:

1. can introduce two more methods and deprecate the old ones. 
        +: backward compatibility
         -: too many methods
2. we can replace the old methods with the new names, but it will be breaking changes. 
         +: backward incompatibility
         -: nicer api

**Comment by Emily-Jiang** [comment]
We discussed in today's hangout. The consensus is that we leave it for now. The method change exercise will take a lot of effort for no a significant gain. In the next major release, we can reconsider it.

**Comment by Emily-Jiang** [comment]
We discussed this again in today's hangout and decide not to do it as there is no apparent advantages.
