### ISSUE TITLE
FallbackHandler's ExecutionContext should provide Exception getter

### ISSUE THREAD

**Issue by derekm** [eclipse/microprofile-fault-tolerance#224]
`FallbackHandler`'s `ExecutionContext` should provide access to the exception that was caught, for example, here: https://github.com/eclipse/microprofile-fault-tolerance/blob/master/api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java#L103

**Comment by Emily-Jiang** [comment]
Can you explain the use case?

**Comment by antoinesd** [comment]
Understand the possible use cases here (intelligent fallback according exception type). But wouldn't be too overkill ?

**Comment by derekm** [comment]
We kind of want to notify our callers that a fault occurred, by throwing an exception from the fallback method that the caller can catch for fault details. In order to notify callers of exceptional events, we need our fallback to know about these exceptional events.

We also had ideas about fallbacks that didn't notify their callers but that handled different errors more intelligently. Of course this could handled in another way by methods-under-fault doing work before throwing exceptions that trigger MicroProfile Fault Tolerance, but that's actually overkill also (burdening the user-programmer with disparate error-handling logic rather than unifying the error handling logic into the fallback).

Of course, we're finding other approaches since both of these ideas are infeasible right now.

**Comment by Emily-Jiang** [comment]
In microservice architecture, if service A invokes service B unsuccessfully, all you get is the 404. You won't know the actual exception though.

**Comment by derekm** [comment]
Great! Thanks! This will be helpful in the future!

FWIW, for our main situation, we moved our operation that needs Fault Tolerance into an ObserveAsync listener, and we assume the process has failed until it succeeds (that is, we write out "not succeeded" before `fireAsync()` until a success writes out "succeeded", instead of our fallback handler writing out "failed" when it has failed).
