### ISSUE TITLE
Fallback method and unused sonar method

### ISSUE THREAD

**Issue by RadoslawOsinski** [eclipse/microprofile-fault-tolerance#225]
In examples from blog:
http://blog.payara.fish/preview-microprofile-fault-tolerance-in-payara-micro
there is example for Fallback annotation usage:
```
@GET
    @Fallback(fallbackMethod = "getAllEmployeesFallback")
    @Timeout(TIMEOUT)
    public String getAllEmployees() throws InterruptedException {
        if (isSlow()) return employees.toString();
        return employees.toString();
    }

    public String getAllEmployeesFallback() {
        return "It took longer than expected to get all employees. Try again later!";
    }
```
I have not checked but I believe it works as described. In my current project code is analyzed by Sonar. During code analysis there was broken rule "Unused method". I am looking for other code examples which would allow me to pass this sonar rule.

In my opinion it is **not** a problem of microprofile project. Same problems exists in competing hystrix project described for example here:
https://spring.io/guides/gs/circuit-breaker/
with example code:
```
  @HystrixCommand(fallbackMethod = "reliable")
  public String readingList() {
    URI uri = URI.create("http://localhost:8090/recommended");
    return this.restTemplate.getForObject(uri, String.class);
  }

  public String reliable() {
    return "Cloud Native Java (O'Reilly)";
  }
```
This example I have checked in sonar few months ago. This small problem in corporate environment discredits this kind of fallback solution. Could you suggest how to solve this problem? 

**Ondro Mihályi** kindly wrote some ideas how It could be solved:
https://twitter.com/OMihalyi/status/960501265569583107

I do not know is it worth to implement. Maybe this issue should be passed to Sonar project. Also I agree with Ondro Mihályi that java annotations may be not flexible enough in this area.

By this issue I wanted only to point a general problem. I hope I was not rude to Ondro Mihályi. I apologise if this tweet was interpreted in such way.

**Comment by Emily-Jiang** [comment]
@RadoslawOsinski thanks for bringing this up! If you have to pass sonar rule, you can use the other flavour of [fallback]( https://github.com/eclipse/microprofile-fault-tolerance/blob/master/api/src/main/java/org/eclipse/microprofile/faulttolerance/FallbackHandler.java)

**Comment by antoinesd** [comment]
IMO sonar rules need to be relax. It's not MP or FT issue as similar issues could appeared with CDI for instance with observer methods. There are not called directly ut by the framework.

**Comment by derekm** [comment]
We're having tons of issues with PMD & SpotBugs in CDI-enabled environments! I almost want to kick the static analyzers to the curb, because all they're doing is forcing us to litter our code with magical incantations that do nothing but allow our builds to pass.

**Comment by RadoslawOsinski** [comment]
Thank you @Emily-Jiang. I haven't seen "FallbackHandler" interface. That solves issues with sonar rules for my team. I belive this question is solved by @Emily-Jiang.
