### ISSUE TITLE
Asynchronous interceptors for reactive apps

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-fault-tolerance#239]
All FT intereceptors in FT 1.1 are synchronous, meaning they wait for the downstream method to return and then do some action, e.g. retry on exception.

In reactive applications this doesn't work because the method usually just triggers an asynchronous action (e.g. asynch JAX-RS call) and the processing continues in a callback of a completion stage.

FT interceptors should support this scenario by doing some post action not after the downstream method returns but after the returned `CompletionStage` completes. I also recommend to support not only `CompletionStage` but also reactive streams `Publisher` and `Processor` and optionally also respective classes in JDK 9 Flow API.

**Comment by Emily-Jiang** [comment]
@OndrejM will add tck to make sure @Asynchronous used together with other FT annotations the return value will be evaluated and trigger the necessary FT actions.

**Comment by Emily-Jiang** [comment]
test only

**Comment by OndrejM** [comment]
As I suggested in #250, `@Asynchronous` should have the highest priority and so all other interceptors should happen in a separate thread. This combined with #110 would solve this issue because all interceptors would work automatically with `CompletionStage` when `@Asynchronous` applied. Still some tests are needed to cover this scenario.

**Comment by OndrejM** [comment]
Well, not exactly. Interceptors need to be adjusted to detect also an exception in Future and CompletionStage. Exception handling is clarified in PR #267 but it should also be clarified that all annotations should detect btoh thrown exceptions and those in Future and CS.

**Comment by Emily-Jiang** [comment]
We have the support for CompletionStage now. What is your opinion on the support of JDK9 streams API or even Reactive Streams Operator APIs.

**Comment by Emily-Jiang** [comment]
I think this issue was fixed by MicroProfile 2.0 release and properly sort the interceptors. Please reopen if you think otherwise @OndroMih !
