### ISSUE TITLE
Policies use subclasses of java.lang.Throwable to specify failures

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-fault-tolerance#247]
However, according to the interceptors spec (Business Method Interceptors) around-invoke methods have the following signature:
> Object <METHOD>(InvocationContext) throws Exception

As a result, you cannot e.g. specify `org.eclipse.microprofile.faulttolerance.Retry.retryOn()` to be a custom `Throwable` (other than `java.lang.Error`and `java.lang.Exception`). A CDI container usually wraps such `Throwable` in a runtime exception.

The spec should probably specify that only exceptions and error are supported.

**Comment by Emily-Jiang** [comment]
yes, we can clarify this in the spec.
