### ISSUE TITLE
Does Timeout on synchronous operation make sense ?

### ISSUE THREAD

**Issue by antoinesd** [eclipse/microprofile-fault-tolerance#248]
In our implementation we are experiencing issue with timeout if it's used on non asynchronous operation.
So I'm wondering if it's relevant to support `@Timeout` on non `@Asynchronous` operations. Any thought ?

**Comment by hutchig** [comment]
Forgive the simplistic language, it is how my mind works.

I imagine it is related to how interruptable the application operation is. 

Perhaps if a method was a local front end for something that is a remote operation,
waiting for the remote operation is locally interruptable, so setting a timeout could be a(nother) way
of controlling how long the application method is allowed to wait for a reply. 

When I look at something like 
https://stackoverflow.com/questions/22672664/setting-request-timeout-for-jax-rs-2-0-client-api
what strikes me is the number of different 'ways' of doing it and how the level of abstraction
relates to the particular call technology used. MicroProfile FaultTolerance Timeouts are perhaps a bit more tech-neutral and cover any cause for the delay in the whole method being timed out not just for a particular single call it might be making.

**Comment by Emily-Jiang** [comment]
@antoinesd it makes sense on synchronous calls if the work being done is interruptible. In the worst scenario, if the thread ignores the interruption, the thread will return when it finishes.
