### ISSUE TITLE
Clarify @Asynchronous @Retry @Bulkhead

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-fault-tolerance#250]
> When using the thread pool approach, when a request cannot be added to the waiting queue, BulkheadException will be thrown.

However, if `@Retry` is also used, it might not be possible to throw the `BulkheadException` immediately. E.g. in the following example, if the first invocation fails due to some networking problem and the second invocation fails due to bulkhead, we cannot throw the `BulkheadException` when `ping()` completes from the client point of view. The only thing we can do is to "throw" the `BulkheadException` via `Future.get()` and `ExecutionException`.

````java
    @Asynchronous
    @Bulkhead(value = 5)
    @Retry(maxRetry = 4)
    public Future<String> ping() {
        // do some networking... 
        return CompletableFuture.completedFuture("ok");
    }
````

**Comment by mkouba** [comment]
I think we should use a wording similar to timeout:
> When @Timeout is used with @Asynchronous, then a separate thread will be spawned to perform the work in the annotated method or methods, while a Future is returned on the main thread. If the work on the spawned thread does timeout, then a get() call to the Future on the main thread should throw an ExecutionException that wraps a fault tolerance TimeoutException.

**Comment by mkouba** [comment]
It seems there are few tck tests (`BulkheadAsynchRetryTest#testBulkheadClassAsynchronous55RetryOverload`, `BulkheadAsynchRetryTest#testBulkheadMethodAsynchronous55RetryOverload`, `BulkheadAsynchRetryTest#testBulkheadMethodAsynchronousRetry55Trip`) which expect the `BulkheadException` to be thrown direcly from an `@Asynchronous` `@Retry` `@Bulkhead` method invocation. This is IMHO wrong, although I'm aware of the fact that even WildFly Swarm impl does support this ATM (we're working on major refactoring so that our impl is more correct and supports all required features).

I hereby request to exclude the aforementioned tests from MP FT 1.0 TCK (i.e. an impl should be allowed to exclude this tests when running the TCK).

@Emily-Jiang @antoinesd WDYT?

**Comment by Emily-Jiang** [comment]
@mkouba can you join the call on 2nd May to discuss the async issues?

**Comment by Emily-Jiang** [comment]
We would like to discuss the real use case you are concerning about.

**Comment by mkouba** [comment]
@Emily-Jiang Ok, I will try to make it.

**Comment by antoinesd** [comment]
@Emily-Jiang. Want to be sure that you are talking about weekly FT meeting on Wed at 2:00pm UK time.

**Comment by Emily-Jiang** [comment]
Let's discuss it in next week's FT hangout on Wed 2:00UK time. sorry..... rescheduled this week's call.

**Comment by OndrejM** [comment]
I agree with @mkouba - asynchronous methods should return asynchronous result and also **throw exceptions asynchronously**. An exception is an alternative return type and should behave as the normal return type unless there are specific needs to throw them directly.

The spec now says:

> The @Asynchronous annotation can be used together with @Timeout, @Fallback, @Bulkhead and @Retry. Method invocation will occur in a different thread.

I would change this to "Method invocation and all the 4 FT interceptors will occur in a different thread".

That would imply that `@Bulkhead` also happens on another thread and hence doesn't throw an exception but finish the future with an exception.

This would make even more sense when we add `CompletionStage` support, where an exception handler would be called in a separate thread.

**Comment by OndrejM** [comment]
We should also define the priority/order of all annotations and `@Asynchronous` should have the highest priority. But this is for another issue.

**Comment by Emily-Jiang** [comment]
As for today's hangout, the current proposal is:

If @Bulkhead used with @Async and @Retry, when BulkheadException occurs, which will trigger the Retry, the execution of Retry will happen on the calling thread.

**Comment by Emily-Jiang** [comment]
please take a look and share your comments.

**Comment by mkouba** [comment]
I've been thinking about this for a while and I don't [this proposal](https://github.com/eclipse/microprofile-fault-tolerance/issues/250#issuecomment-385980500) is a good idea. It would be much clearer if we follow @OndrejM's proposal, i.e. if `@Asynchronous` is present then all policies are applied asynchronously in a different thread -> a call site always gets `Future` (in fact `CompletionStage` would make much more sense) and all exceptions are wrapped in `ExecutionException`. Otherwise we would have to add similar "special handling".

**Comment by Emily-Jiang** [comment]
@mkouba your comment was taken into consideration and all subsequent execution will happen in a separate thread. see #291 for the decision on the combination of annotations and their behavior.

**Comment by antoinesd** [comment]
After checking with @mkouba we can close this issue. Further discussion may happen on #291
