### ISSUE TITLE
Build fails with Checkstyle errors

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-fault-tolerance#252]
"There are 24 errors reported by Checkstyle":
```
DisableAnnotationGloballyTest.java:77: error: Line is longer than 150 characters (found 154).
DisableAnnotationGloballyTest.java:84:9: error: '}' at column 9 should be alone on a line.
DisableAnnotationGloballyTest.java:113:13: error: '}' at column 13 should be alone on a line.
DisableAnnotationGloballyTest.java:138:9: error: '}' at column 9 should be alone on a line.
DisableAnnotationGloballyTest.java:141:9: error: '}' at column 9 should be alone on a line.
DisableAnnotationOnClassTest.java:60: error: Line is longer than 150 characters (found 153).
DisableAnnotationOnClassTest.java:61: error: Line is longer than 150 characters (found 159).
DisableAnnotationOnClassTest.java:62: error: Line is longer than 150 characters (found 152).
DisableAnnotationOnClassTest.java:63: error: Line is longer than 150 characters (found 155).
DisableAnnotationOnClassTest.java:77: error: Line is longer than 150 characters (found 154).
DisableAnnotationOnClassTest.java:84:9: error: '}' at column 9 should be alone on a line.
DisableAnnotationOnClassTest.java:113:13: error: '}' at column 13 should be alone on a line.
DisableAnnotationOnClassTest.java:138:9: error: '}' at column 9 should be alone on a line.
DisableAnnotationOnClassTest.java:141:9: error: '}' at column 9 should be alone on a line.
DisableAnnotationOnMethodsTest.java:59: error: Line is longer than 150 characters (found 155).
DisableAnnotationOnMethodsTest.java:60: error: Line is longer than 150 characters (found 162).
DisableAnnotationOnMethodsTest.java:61: error: Line is longer than 150 characters (found 168).
DisableAnnotationOnMethodsTest.java:62: error: Line is longer than 150 characters (found 161).
DisableAnnotationOnMethodsTest.java:63: error: Line is longer than 150 characters (found 163).
DisableAnnotationOnMethodsTest.java:77: error: Line is longer than 150 characters (found 154).
DisableAnnotationOnMethodsTest.java:84:9: error: '}' at column 9 should be alone on a line.
DisableAnnotationOnMethodsTest.java:112:13: error: '}' at column 13 should be alone on a line.
DisableAnnotationOnMethodsTest.java:137:9: error: '}' at column 9 should be alone on a line.
DisableAnnotationOnMethodsTest.java:140:9: error: '}' at column 9 should be alone on a line.
```

**Comment by mkouba** [comment]
Moreover, there are errors while generating javadoc:
```
ERROR] Exit code: 1 - /opt/source/swarm/microprofile/microprofile-fault-tolerance/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationGloballyTest.java:152: warning: no description for @throws
[ERROR]      * @throws InterruptedException
[ERROR]        ^
[ERROR] /opt/source/swarm/microprofile/microprofile-fault-tolerance/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationGloballyTest.java:43: error: unknown tag: auhtor
[ERROR]  * @auhtor Antoine Sabot-Durand
[ERROR]    ^
[ERROR] /opt/source/swarm/microprofile/microprofile-fault-tolerance/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnClassTest.java:153: warning: no description for @throws
[ERROR]      * @throws InterruptedException
[ERROR]        ^
[ERROR] /opt/source/swarm/microprofile/microprofile-fault-tolerance/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnClassTest.java:43: error: unknown tag: auhtor
[ERROR]  * @auhtor Antoine Sabot-Durand
[ERROR]    ^
[ERROR] /opt/source/swarm/microprofile/microprofile-fault-tolerance/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnMethodsTest.java:151: warning: no description for @throws
[ERROR]      * @throws InterruptedException
[ERROR]        ^
[ERROR] /opt/source/swarm/microprofile/microprofile-fault-tolerance/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnMethodsTest.java:43: error: unknown tag: auhtor
[ERROR]  * @auhtor Antoine Sabot-Durand
[ERROR]    ^
[ERROR] /opt/source/swarm/microprofile/microprofile-fault-tolerance/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsynchronousTest.java:42: warning: no description for @author
[ERROR]  * @author
[ERROR]    ^
```

I think it would be wise to add some basic CI, e.g. https://travis-ci.org/. @Emily-Jiang @antoinesd WDYT?

**Comment by Emily-Jiang** [comment]
Just saw the build errors myself.... @mkouba @antoinesd it is best to run a local build just with mvn clean install to verify your PRs. I'll do a fix on this if I have time today.

**Comment by mkouba** [comment]
@Emily-Jiang of course it is but a PR check (e.g. using Travis CI) would be a safety bell.

**Comment by hutchig** [comment]
I have these edits already and am happy to do a PR.

**Comment by hutchig** [comment]
https://github.com/eclipse/microprofile-fault-tolerance/pull/255

**Comment by Emily-Jiang** [comment]
ah. didn't see your message @hutchig ! I have just fixed the build. @mkouba all errors should be caught by simply running mvn clean install. I think @antoinesd might have disabled some style check, which is why the build is broken in the travis. @antoinesd can you make sure not to set other parameters to verify your PR is good.

**Comment by hutchig** [comment]
No problem :-)

**Comment by hutchig** [comment]
My PR also had a fix for the
tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsynchronousTest.java empty @author which was giving me
[WARNING] /Users/hutchig/git/eclipse/microprofile-fault-tolerance/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsynchronousTest.java:42: warning: no description for @author
[WARNING] * @author

**Comment by Emily-Jiang** [comment]
Based on our discussion, can I close this issue @mkouba  or you want to pull in more infrastructure changes

**Comment by mkouba** [comment]
I still think that a PR check (e.g. using Travis CI) would be beneficial.

**Comment by antoinesd** [comment]
+1
To be honest I'm a bit puzzled that no MP spec use a CI for PR like Travis. Didn't find any decision on that point

**Comment by Emily-Jiang** [comment]
The problem mentioned in this issue can be resolved via `mvn clean install` on the local run. If you think MP infrastructure should introduce Travis CI against PR, please feel free to raise on MP mailinglist with another use case where you cannot do it locally and cheaply.

**Comment by mkouba** [comment]
> ...another use case where you cannot do it locally and cheaply.

That's not the purpose of CI and automated builds. The main benefit is that a PR is built automatically and could be rejected immediately if anyone attempts to push changes that would break the build or tests. Otherwise the one who is merging a PR would have to perform all checks manually. And as you can see - manual checks are very often neglected ;-)

@antoinesd Pls send a request/question to the MP ML.

**Comment by Emily-Jiang** [comment]
I'll update FT to use CI plugin to run a build.

**Comment by Azquelt** [comment]
We think this is almost done
 * Emily has enabled the CI plugin
 * @carlosdlr has translated the rules from the pom.xml into an mp-checkstyle.xml file which can be referenced by an IDE to apply the same rules in the editor (#228)

One thing we'd like to change is to make the pom.xml reference the mp-checkstyle.xml file, rather than both files defining the same rules. @carlosdlr will make another PR to do this.

**Comment by Emily-Jiang** [comment]
This can be closed now.
