### ISSUE TITLE
Allow explicit trues in Disabled Fault Tolerance policies with configuration 

### ISSUE THREAD

**Issue by benjamin-confino** [eclipse/microprofile-fault-tolerance#266]
In configuration.asciidoc under Disabled Fault Tolerance policies with configuration there is the following statement:

`If the above configurations patterns are used with another value than `false` (i.e. `<classname>/<methodname>/<annotation>/enabled=whatever`) non-portable behaviour results`.

I believe that the spec should cover the value `true` as well as `false` and state that should the value true explicitly set then it will override a value of false on a higher scope. This will allow you do something like disable the Retry annotation globally but override it for a single method while you debug that method.

**Comment by Emily-Jiang** [comment]
We should improve this. @antoinesd what do you think?
