### ISSUE TITLE
Improve speed and perhaps reliability of the Bulkhead TCK tests.

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-fault-tolerance#271]
Many of the Bulkhead TCK tests 'count' how many threads are in the bulkhead at
once. This is often done by starting them all at the same time and each method
taking a perion of time using, for example, a sleep. 

Very rarely I see a test fail due to not 'enough' parallelism, (for example in the current TCK  testBulkheadClassSemaphore3 seems to be the most common when the whole suite is run
but can be run on it's own many many times with no problem). [ACTUALLY - I DID MORE WORK ON THAT ISSUE I SAW AND BELIEVE IT WAS A PROBLEM IN OUR PROTOTYPE METRICS INTEGRATION IMPLEMENTATION BUT THIS CHANGE WOULD STILL BE AN IMPROVEMENT AS IT WOULD SPEED UP THE TESTS REF: https://github.com/OpenLiberty/open-liberty/issues/3100]

It would be better to insert some sort of join/latch.await to ensure a level of parallelism
that can be robustly checked for 100% - this will also enable the tests to run faster as well as more
reliably.

**Comment by hutchig** [comment]
Having put in tighted concurrency controls, I now have a working theory that I am testing that
this may be occurring due to the Bulkhead3ClassSemaphoreBean being application
scoped and there being leftover 'workers' in the Bulkhead from previous tests.

**Comment by Azquelt** [comment]
When we look at these tests, we should see if we can make it easier to understand how the tests work and what they are checking for. See #420

**Comment by Emily-Jiang** [comment]
@carlosdlr will modify more tests.

**Comment by Azquelt** [comment]
The Bulkhead tests take about 25% of the total runtime when running on liberty and 58% of the total runtime on smallrye. (Liberty uses a managed arquillian container so there's more overhead deploying applications).

Bulkhead doesn't have any inherent dependency on time passing (unlike Timeout, Retry and CircuitBreaker) so it's hard to justify having the tests take this long.

It's still the area of the tests that we should be targeting if we want to reduce the time it takes to run the TCK. We don't necessarily need to do any more work on this for 2.1, but there's certainly more that could be done to reduce the time that the tests take.

**Comment by Azquelt** [comment]
@jbee pointed out on gitter that many of the bulkhead tests throw a lot of tasks at a bulkhead method and then check that at some point the bulkhead was filled. This can occasionally be a problem on a busy CI system, or if the runtime limits the amount of concurrent tasks in another way.

I'm not sure that being able to fill the bulkhead when running under load is required for correct operation (certainly desirable, but not required), so we should probably remove this check when we're revisiting the bulkhead tests.

**Comment by jbee** [comment]
@Azquelt Let me add that this isn't just a problem on CI. Especially when work is executing fast there is a tendency to not "catch" the threads while they are in the method body so that the bulkhead is never observed as filled even if that was the case in the limits set by the OS scheduling.

**Comment by Azquelt** [comment]
I guess that's possible, but in the TCK, I think everything that's supposed to be observed inside the bulkhead sleeps for at least a second. I didn't _think_ there were any tests where tasks are expected to enter and then exit the bulkhead very quickly though I could be mistaken there.
