### ISSUE TITLE
CDI request context should be active during @Asynchronous method invocation

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-fault-tolerance#274]
Just like it's active during an asynchronous method invocation of an EJB session bean.

**Comment by Emily-Jiang** [comment]
@mkouba is this a spec clarification?

**Comment by mkouba** [comment]
Yes, it is.

**Comment by Emily-Jiang** [comment]
Will add clarify to the spec and add a tck with `@RequestScoped` bean to demonstrate this.
