### ISSUE TITLE
Thread pool-based bulkheads with JAX-RS asynchronous resources

### ISSUE THREAD

**Issue by sdaschner** [eclipse/microprofile-fault-tolerance#297]
In order to implement thread pool-based bulkheads that originate from HTTP / REST endpoints, it would be very helpful to use executor services, provided by MP FT from JAX-RS asynchronous resources.

I showcased the idea to implement both bulkheads and also threadpool-based backpressure, in the following video: https://blog.sebastian-daschner.com/entries/bulkheads-backpressure-javaee

As far as I've understood and tried the specification, this isn't possible right now using MP FT (right?), that's why I used Adam Bien's Porcupine.

It would be very beneficial for API users to a) somewhat get access to container-managed executor services, similar to Porcupine, that are also configurable, e.g. in regard to rejection policy, and/or b) return a `CompletionStage` / `CompletableFuture` that under-the-hood uses a managed thread pool. The motivation is to "connect" the request thread pool with the managed, asynchronous execution to pass over the request handling and not utilize a request thread for the whole execution.

This might be related to #250 and others. Please comment

**Comment by Emily-Jiang** [comment]
@sdaschner this is related to issue #110 . We are also in [discussion](https://groups.google.com/forum/#!topic/microprofile/jKFu-IS_U90) to bring concurrency to MP due to the usage of #110 .

**Comment by Emily-Jiang** [comment]
@sdaschner can you review the PR #267  to see whether it addresses your problem. If yes, please close this issue. If not, please explain a bit more so that we can understand your use case better.

**Comment by sdaschner** [comment]
Thanks for the update!

Yes, the changes LGTM for what I'm having in mind with JAX-RS. I'll test that new version of FT once it'll be available.

However, we might want to consider adding a possibility to define (lower-level) managed ExecutorServices for more flexible scenarios as well in a future release.
