### ISSUE TITLE
Should Asynchronous methods be allowed to have a void return type

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-fault-tolerance#298]
Should we allow this?
```
public class MyClass() {
    @Asynchronous
    public void myMethod() { }
}
```

I don't think there's a need to require the user to return a future or a completion stage if they just want to fire and forget some operation.

**Comment by Emily-Jiang** [comment]
@brunobat and I discussed this on today's hangout. We think all declared methods must return a future or completion stage. If the return is void, it should Future<Void> or CompletionStage<Void>

**Comment by Azquelt** [comment]
Fair enough

**Comment by sdaschner** [comment]
Sorry for re-opening this, but could you elaborate further what was the outcome of the discussion? While developers can always declare a `CompletionStage<Void>`, I don't see any disadvantage in supporting `void` as valid return type as well.
