### ISSUE TITLE
Create CircuitBreaker Functionality

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#3]
The ability to fail an invocation fast based on known failure state of the component, both annotation and programmatic fashions.

**Comment by jGauravGupta** [comment]
`failThresholdPercentage` should be introduced to activate circuit breaker based on failure percentage instead of failure count.
`long failThresholdPercentage() default 50;`
e.g if 50%+ (A%+) of requests in 10 (B) seconds are failures then open the circuit.
