### ISSUE TITLE
CircuitBreakerTest.testCircuitDefaultSuccessThreshold, CircuitBreakerTest.testCircuitInitialSuccessDefaultSuccessThreshold, and CircuitBreakerTest.testCircuitLateSuccessDefaultSuccessThreshold tests need splitting up.

### ISSUE THREAD

**Issue by Pandrex247** [eclipse/microprofile-fault-tolerance#302]
These three tests all check the behaviour of a circuit breaker as it "fills up". Individually they are fine, but when you run all of the test methods sequentially (such as what would happen if you used _mvn clean test_) these three tests foul each other up. This is due to each of them using the same bean class and method and expecting it to have a "clean" circuit breaker - as in, an unused one.

So when running them sequentially (in typical alphabetical order), you can end up with the following:

1. _testCircuitDefaultSuccessThreshold_ runs successfully, leaving the circuit in an open state.
2. _testCircuitInitialSuccessDefaultSuccessThreshold_ runs. The circuit is either in an open or half-open state depending on how quickly this starts. This can lead to either a _CircuitBreakerOpenException_ on the first request, or the first request being used to close the circuit again, and then the test failing on the fifth iteration as it expects a _CircuitBreakerOpenException_ which it won't get as this fifth request is the request which actually opens the circuit. This leaves the circuit in an open state.
3. _testCircuitLateSuccessDefaultSuccessThreshold_ runs. The circuit is, again, either in an open or half-open state depending on how quickly this starts, leading to it failing in a similar manner to point 2.

As far as I understand it, this is expected behaviour as the circuit shouldn't be getting reset due to the requests from each of these tests going to the same deployment of the same application.

**Comment by Azquelt** [comment]
`CircuitBreakerClientDefaultSuccessThreshold` is `RequestScoped`.

Generally this means you get a new instance for each test, but I'm not sure if that's a side effect of Arquillian making a request for each test when using the servlet protocol.

If there are cases where we don't get a new instance for each test, we could change it to a dependent bean and inject a separate instance for each test instead.

**Comment by Pandrex247** [comment]
Is it expected behaviour then that if you have two instances of the same bean that they don't share the same circuit breaker?

As I understood the spec the annotations were tied to the actual methods, so that each instance of a bean that calls an annotated method would share the same circuit breaker.

**Comment by Emily-Jiang** [comment]
yes to your question @Pandrex247

**Comment by Emily-Jiang** [comment]
If you are happy with the answer, please close this issue. Thanks for reporting this!

**Comment by Pandrex247** [comment]
Yep, thanks :)

**Comment by rmannibucau** [comment]
Hello,

can we reopen this issue please? request scoped is undefined in arquillian and using an embedded container you hit easily that issue so I guess the bean should be duplicated or some pause should be added in between tests

**Comment by Ladicek** [comment]
I've opened #479 to clarify this in the spec. That's where it belongs.
