### ISSUE TITLE
Can Fallback be used without Retry or CircuitBreaker?

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-fault-tolerance#310]
Can you use `@Fallback`, either on its own or in conjunction with `@Bulkhead`, `@Asynchronous` or `@Timeout`

Currently the spec initially says that `@Fallback` can be used once `@Retry` or `@CircuitBreaker` has failed enough. It then later says
> The fallback should be triggered when an exception occurs. For instance, `BulkheadException`, `CircuitBreakerOpenException`, `TimeoutException` should trigger the fallback.

In the TCK tests, `@Fallback` is always used with `@Retry`, except in `FallbackMetricBean` which is only trying to tests metrics.

Can we either specify that `@Fallback` can be used both alone and with any combination of other FT annotations, or define what should happen if it's used without `@Retry` or `@CircuitBreaker`?

Either way, we should add some TCKs.

**Comment by kenfinnigan** [comment]
I've used `@Fallback` on its own, so that should definitely be made clear that that is permissable

**Comment by Emily-Jiang** [comment]
we should add spec clarification and tck

**Comment by Azquelt** [comment]
@brunobat is happy to work on this, is that ok with you @Emily-Jiang ?

**Comment by Azquelt** [comment]
Looks like this has been completed, thanks @brunobat
