### ISSUE TITLE
Retry: What happens when delay is less than jitter?

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-fault-tolerance#312]
The `@Retry` javadoc says that a random value between `jitter` and `-jitter` is added to `delay` to find out how much delay should be applied to each retry attempt.

What happens when the value of `delay` is less than the value of `jitter`?

This question is particularly pertinent because the default configuration has `delay=0ms, jitter=200ms`. Obviously we can't delay for `-200ms`, but what is the expected behaviour?

**Comment by Azquelt** [comment]
Personally, I think that if `delay=0` then there should be no delay. I can see the following options:

* Make it invalid for jitter to be less than delay. Change the default jitter to 0.
* Specify that jitter is set to the same value as delay if jitter is greater than delay.

**Comment by Emily-Jiang** [comment]
@antoinesd and Bruno to check the current behavior on Thorntail and Safeguard and rediscuss

**Comment by Emily-Jiang** [comment]
@brunobat to contribute tcks.

**Comment by Azquelt** [comment]
I think this has been cleared up, thanks :)
