### ISSUE TITLE
Specify interactions with AroundInvoke interceptors

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-fault-tolerance#313]
How does Fault Tolerance interact with `@AroundInvoke` interceptors?

* Does fault tolerance happen before other interceptors?
should it be lib_after(3000, open liberty) or lib_before (1000, thorntail), safeguard (400)?

We agree on to set the initial value of platform_after + 10 (4010)
Transactional - 200

@Retry
@MyLog(3)
@MyPrint(4)
public void myInvok() {

...
}
1. log->print->FT->method
most desired sequence.
2. FT->log->print->method

3. log->FT->print->method

* after?
* Is it itself in an interceptor with a specific priority?
  * Is the priority configurable?
* How do we expect other interceptors to be called when used with
  * `@Retry` (interceptors later in the chain get called more than once?)
  * `@Asynchronous`
    * Interceptors later in the chain get called on another thread?
    * Interceptors later in the chain see the result from the method?
    * Interceptors earlier in the chain see the result placeholder returned by fault tolerance?
    * Interceptors earlier in the chain may be called and return before the invocation of the method actually starts?
  * `@CircuitBreaker` (interceptors later in the chain may not get called at all?)
  * `@Timeout` (interceptors later in the chain are included in the the timeout timer, any results they return may get discarded in favor of a TimeoutException?)

Implementation note: If Fault Tolerance is implemented as an interceptor, then the InvocationContext needs to tolerate an interceptor that
* Doesn't call `proceed()` at all
* Calls `proceed()` more than once
* Calls `proceed()` from a different thread after the interceptor method has returned

**Comment by Emily-Jiang** [comment]
mp.fault.tolerance.interceptor.priority=Priority.PLATFORM_AFTER+10 use this property to configure the priority if necessary

**Comment by Emily-Jiang** [comment]
How do we expect other interceptors to be called when used with

    @Retry (see above)
    @Asynchronous
        Interceptors later in the chain get called on another thread? yes
        Interceptors later in the chain see the result from the method? yes
        Interceptors earlier in the chain see the result placeholder returned by fault tolerance? yes
        Interceptors earlier in the chain may be called and return before the invocation of the method actually starts? yes
    @CircuitBreaker (interceptors later in the chain may not get called at all?) yes
    @Timeout (interceptors later in the chain are included in the the timeout timer, any results they return may get discarded in favor of a TimeoutException?) yes

**Comment by Emily-Jiang** [comment]
Revisit this issue to see what @antoinesd @brunobat find out the behaviour on Thorntail and TomiEE for placing CDI interceptors mixed with Fault Tolerance annotations on EJB beans. See code example https://github.com/Azquelt/open-liberty/blob/ejb-ft-async-bug/dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/ejb/FaultToleranceEjbTestServlet.java

**Comment by Emily-Jiang** [comment]
@carlosdlr please contribute tcks for this.
