### ISSUE TITLE
Does @Timeout clear the Thread interrupted flag when the method returns

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-fault-tolerance#322]
Then `@Timeout` is used, the thread is interrupted with `Thread.interrupt()`. Ideally the method checks this flag, or is running some waiting method which will throw an `InterruptedException`.

However, it's possible for the method to ignore this, which would result in the interrupted flag still being set when the method eventually returns.

Should we specify that fault tolerance should clear the flag when the method returns if a timeout has occurred?

**Comment by Emily-Jiang** [comment]
The consensus on today's call is: we should clarify in the spec and add the tck tests.

**Comment by Azquelt** [comment]
#333 adds this test for synchronous execution. It's not possible to test for asynchronous execution because you can't get hold of the work thread after fault tolerance has finished with it. I'll make a new PR to also update the spec.
