### ISSUE TITLE
TCK CircuitBreakerTest - test methods reusing CircuitBreakerClientDefaultSuccessThreshold#serviceA()

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-fault-tolerance#323]
Specifically `testCircuitInitialSuccessDefaultSuccessThreshold()`, `testCircuitLateSuccessDefaultSuccessThreshold()` and `testCircuitDefaultSuccessThreshold()`. 

This is not correct as the tests may affect each other. E.g. `testCircuitDefaultSuccessThreshold()` leaves the CB OPEN... 

Note that there is no portable way to reset the CB state for a particular bean/method. 

The bean could be reused but every test should be performed in a different deployment so that it is certain that the CB is in its inital state.

**Comment by Azquelt** [comment]
@carlosdlr will update these tests

**Comment by Emily-Jiang** [comment]
thanks @carlosdlr !
