### ISSUE TITLE
TCK - BulkheadMetricTest#bulkheadMetricHistogramTest() sleeps for 3 seconds?

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-fault-tolerance#337]
See also https://github.com/eclipse/microprofile-fault-tolerance/blob/1.1.2/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricTest.java#L162

I don't think that any tck test should sleep for 3 seconds. And if it's really needed, it should be well described why it is needed and the value should be probably a configurable property so that it would be possible to scale the value depending on the machine performance.

**Comment by Azquelt** [comment]
The idea of this test is to test the bulkhead execution time histogram metric. It reports the spread of execution times for invocations of the method.

To test it, we need a set of executions which takes a spread of times. The test runs two executions which take three seconds (in parallel) and then runs 10 that should take negligible time.

We then check that the histogram reports that the fastest 75% of executions were all under 100ms, while the fastest 99% of executions were all under 3000ms (+-100ms).

Where the spec defines anything time-based (either time metrics or the `@Timeout` annotation), I don't think we can get away without doing waits in the test, though I'm open to suggestions.

A configurable property is a reasonable idea, and could probably be implemented here.

In other areas of the spec that would be harder and we might have to rely on support for configuration via mpConfig as a prerequisite for all of the `@Timeout` tests.

Do you have an idea of how other specs handle this sort of property? I assume for this test we could add a scaling factor which would adjust both the sleep time and the tolerance?

**Comment by mkouba** [comment]
I understand that it's not easy ;-). My point is that if there is a lot of similar tests then running the whole test suite is more time consuming and that usually leads to `-DskipTests`.

For this particular test I would suggest to lower the value to 1000ms. It should be enough, or?

In CDI TCK there is a property called [testTimeoutFactor](https://github.com/cdi-spec/cdi-tck/blob/master/api/src/main/java/org/jboss/cdi/tck/api/Configuration.java#L140) - a percentage value that is used to adjust the delay in all tests using timeout. The default value is 100. So e.g. if a test machine is slower you can set this value to 200 and all delays will take 2x longer. I'm not sure about the tolerance though - what would it be used for?

**Comment by Azquelt** [comment]
For example, in this test we expect the method call to take 3000ms but, to allow for small variations in machine speed and load, when we do the check we allow a tolerance of 100ms, so that any value between 2900ms and 3100ms is acceptable.
