### ISSUE TITLE
Inconsistency between CircuitBreaker.failureRatio() javadoc and spec example

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-fault-tolerance#341]
Javadoc:
> The failure threshold to trigger the circuit to open. e.g. if the requestVolumeThreshold is 20 and failureRation is .50, **more than 10 failures** in 20 consecutive requests will trigger the circuit to open. The value must be between 0 and 1 inclusive.

However, according to the example in the **8.1. Circuit Breaker Usage** - quoted below - **10 and more failures** (20x0.5) should open the circuit.

Circuit Breaker Usage example with `requestVolumeThreshold = 4, failureRatio=0.75`:
> The above code-snippet means the method serviceA applies the CircuitBreaker policy, which is to open the circuit once 3 (4x0.75) failures occur among the rolling window of 4 consecutive invocation.

According to the javadoc above **more than 3 failures** should open the circuit.

**Comment by Emily-Jiang** [comment]
will fix the inconsistency in the spec.
