### ISSUE TITLE
Asynchronous handling

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-fault-tolerance#35]
In supporting of Asynchronous method invocation, there are a few options. We need to agree on which one is the best approach or add more ideas.

- Use the callback mechanism

 The method must declare the void return type, while the return value passed via the callback.
``` 
@Asynchronous(MyCallback.class)
public void myService(){
...
}

public class MyCallback implements AsyncCallback{
..
}

public interface AsyncCallback<T>{
      boolean isComplete();
      T getObject();
}
```
The result will be passed to MyCallback

- all return a Future: Enforce method to return Future<T> - easier approach for calling point, but not very clean for the dev creating the method. Method should return null or a false Future since the interceptor will do the real job. This approach also prevent using existing class method in async mode (adding @Asyncrhonous with a portable extension for instance)

- method signature unchanged but the return will be a proxy

- Introduce a specific Future in the API: AsyncFuture<> like it's done for EJB asynchronous call. 

-  Use Object return type. More versatile but not clean from calling side 

-  Accept any return type and have the interceptor return null and sending the Future<> in a monitoring bean. (this is effectively same as the first option?)

**Comment by Ladicek** [comment]
In a special case where the async method has no return value and there's no desire to wait for completion ("fire and forget"), `void` is obviously the best choice. But in general, I think async methods should just return `CompletableFuture`. It actually allows composing multiple async calls, which would be much clunkier with other approaches. The simplest implementations that don't call other async methods would just `return CompletableFuture.completedFuture(value)`, and more complex implementations can use all the `CompletableFuture` API. (I'm not particularly fond of `CompletableFuture`'s API, but it's probably the best choice if you don't want to adopt RxJava.)

**Comment by Emily-Jiang** [comment]
Thanks @Ladicek ! We will experiment what you have suggested.

**Comment by Emily-Jiang** [comment]
Just report back. We tried to prototype the 2nd choice (mentioned in Antoine's notes as well) to force the method with @Asynchronous to return a Future using what @Ladicek 's suggestion of CompletableFuture. It does work. I think so far most people prefer this. The nice thing is "no api changes involved but just javadoc". I'll do a PR to spec this in the Async javadoc.

**Comment by Emily-Jiang** [comment]
Updated the Asynchronous javadoc.

**Comment by OndrejM** [comment]
Going through the API now (I'm sorry I didn't have any time to follow what's going on earlier), I see that the asynchronous API only supports returning `Future`. Although the examples all use `CompletableFuture` as a return value, processing the returned value is only possible as `Future`. Why doesn't the API also support `CompletionStage` return value, which would allow chaining asynchronous calls?

As an example, the current solution only supports this:

```
@Asynchronous
public Future<Connection> serviceA() {
  return CompletableFuture.completedFuture(connectionService());
}
```

Which can be called as:

```
Future<Connection> futureConn = serviceA();
futureConn.get()    // this is a blocking call, forcing to wait until the async thread finishes)
   .close();
```

If `CompletionStage` was also supported as return type, chaining would be possible in the async thread, without blocking the initial thread:

```
@Asynchronous
public CompletionStage<Connection> serviceA() {
  return CompletableFuture.completedFuture(connectionService());
}
```

Which can be called as:

```
CompletionStage<Connection> futureConn = serviceA();
futureConn.thenAccept(conn -> conn.close());    // conn.close() would be executed in the async thread
continueWithoutBlocking(); // further processing continues without waiting for the async thread
```
If the initial thread still needs to wait for the async result, it can do with the following code: `Connection conn = futureConn.toCompletableFuture().get()`.

Have you discussed this? Should I raise it as an issue for FT 1.1?
