### ISSUE TITLE
TCK using ShouldThrowException should assert on fault tolerance exceptions and not CDI exceptions

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-fault-tolerance#355]
Rational being to not check the CDI container  but the actual behavior (validation mainly)

**Comment by Azquelt** [comment]
Agree, looks like most of the `Invalid******Test` classes are checking for `javax.enterprise.inject.spi.DefinitionException` instead of `org.eclipse.microprofile.faulttolerance.exceptions.FaultToleranceDefinitionException`

**Comment by Azquelt** [comment]
@brunobat will take a look at this
