### ISSUE TITLE
Bean BulkheadRapidRetry55MethodAsynchBean should set jitter

### ISSUE THREAD

**Issue by spericas** [eclipse/microprofile-fault-tolerance#358]
The `@Retry` annotation on `BulkheadRapidRetry55MethodAsynchBean::test` sets a delay of 1 micro second with the intent of retry bulkhead exceptions as quickly as possible. However, the test does not set `jitter` leaving it to its default of 200 ms. 

Without setting `jitter` to a low value in micros, my understanding is that the delay will be affected by the default value of 200 ms. With that variance it's possible for `testBulkheadMethodAsynchronousRetry55Trip` to be experience intermittent failures with our implementation. Either the jitter should be ignored (not sure why) or explicitly set to a lower value to ensure consistency.

Using TCK version 1.0.

**Comment by carlosdlr** [comment]
Hello @spericas This was a known issue and was fixed on TCK 1.1

**Comment by spericas** [comment]
@carlosdlr Could you provide a link to the change or the git tag that I should use? I see some classes are renamed in later versions, but no explicit use of `jitter`.

**Comment by Emily-Jiang** [comment]
@carlosdlr will do a bit more investigation and confirm.

**Comment by Emily-Jiang** [comment]
cool. thanks. Let's close this one.
