### ISSUE TITLE
API should define exception

### ISSUE THREAD

**Issue by antoinesd** [eclipse/microprofile-fault-tolerance#36]
API should define one or more exceptions for common error case (operation in timeout with defined fallback or circuit breaker for instance).

**Comment by Emily-Jiang** [comment]
I was thinking the same recently and tried to prototype but have not raised an issue. I suggest to create a FaultToleranceRuntimeException and it should be thrown when max retries exceeded or circuit is open or timeout occurred. An PR to follow shortly.
