### ISSUE TITLE
Exception management in BulkheadMetricsAsyncTest

### ISSUE THREAD

**Issue by spericas** [eclipse/microprofile-fault-tolerance#372]
TCK version: 1.1.3

Please refer to #357 for background information. Method `BulkheadMetricsAsyncTest::bulkheadMetricAsyncTest` attempts to get a BulkheadException as follows:

```
        Future<?> f1 = bulkheadBean.waitForAsync(waitingFuture);
        Future<?> f2 = bulkheadBean.waitForAsync(waitingFuture);
        bulkheadBean.waitForRunningExecutions(2);
        long startTime = System.nanoTime();
        
        Future<?> f3 = bulkheadBean.waitForAsync(waitingFuture);
        Future<?> f4 = bulkheadBean.waitForAsync(waitingFuture);
        expectBulkheadException(() -> bulkheadBean.waitForAsync(waitingFuture));
```

There are 2 implementations of method `expectBulkheadException()`, one that accepts an `ExceptionThrowingAction` and another that accepts a `Future`. 

The call above uses the former but should likely use the latter. Because this is an async bulkhead, exceptions are expected when `Future::get` is called on the returned future, not when the bean method is called.

**Comment by spericas** [comment]
@Azquelt We are going with test exclusion and 1.1.3 for now. Thanks.

**Comment by spericas** [comment]
@Emily-Jiang I've found issues only in the 3 tests that I already mentioned, one in this issue and the other two in #357.

**Comment by Emily-Jiang** [comment]
ok. I'll exclude the 4 tests in 1.1.4 release.

**Comment by Emily-Jiang** [comment]
I'll try to do it this week.

**Comment by Emily-Jiang** [comment]
@spericas can you review the PR https://github.com/eclipse/microprofile-fault-tolerance/pull/380 to see whether it has addressed all of the issues. Once you approve, I will do a release.
