### ISSUE TITLE
TCK uses currentTimeMillis

### ISSUE THREAD

**Issue by benjamin-confino** [eclipse/microprofile-fault-tolerance#373]
A couple of TCK tests still use `System.currentTimeMillis()` for measuring the time a thread takes. It is recommended that `nanoTime()` is used instead as nanoTime is independent of the system clock and, for example, switching to daylight savings time will not affect the tests.

**Comment by Emily-Jiang** [comment]
fixed by #374

**Comment by Azquelt** [comment]
In some cases, `currentTimeMillis()` was replaced with `nanoTime()` without changing the value which it is compared against, making the expected time a million times shorter than was intended.
