### ISSUE TITLE
Introduce an annotation to configure default operation handler

### ISSUE THREAD

**Issue by antoinesd** [eclipse/microprofile-fault-tolerance#40]
API should introduce an annotation to configure default (i.e non in fallback) operation handler.
This should be done for multiple reason:

* To provide same level of configuration for default operation than we have for fallback
* To allow user to create handler class having implementation specific feature
* Mark method for Fault Tolerance handling with default behaviour (default timeout, fallback, etc...)

This annotation would work like `@Fallback`, we only may have to rename `FallbackHandler` interface to `OperationHandler`

I suggest the following names for this annotation:

* `@FaultToleranceOperation`
* `@FaultToleranceHandler`
* `@FaultToleranceConfiguration` (if we'd like to had impl specific config in a Map member)

I chose the term 'operation' to avoid 'command' which is too  much "Hystrix-ish", but of course another term could be chosen here.

**Comment by Emily-Jiang** [comment]
@ExtendedOperation ? I really want to keep the name Fallback as it is well known.  We could even define fallback is the last one to be invoked. normal operation-> extended operation->if fails, fallback operation. This might introduce some complication. The _ExtendedOperation_ needs to define under what condition it will be called.

**Comment by Emily-Jiang** [comment]
I've renamed the package names as we discussed last week. Feel free to put a PR.

**Comment by antoinesd** [comment]
Ok, I'm on it.
Regarding name and nature fo this annotation, we should really answer the question about having a  method without any FT annotation. I tend to think that such a method should be called in a classical way (no fault tolerance feature on it).
I see this annotation on the simplest way to activate fault tolerance on a method. Optionally you could provide a specific "handler" to manage the fault tolerance operation otherwise the default one will be used.

**Comment by antoinesd** [comment]
Sent a first proposal for this with #61

**Comment by Emily-Jiang** [comment]
Thanks @antoinesd ! Based on our discussion today, let's close this for now.
