### ISSUE TITLE
Improve tests - reduce waste time

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-fault-tolerance#402]
In some tests, there are sleeps added where they don't need to. We need revisit the tests to get rid of sleeps.

**Comment by Emily-Jiang** [comment]
@carlosdlr will work on this.

**Comment by Emily-Jiang** [comment]
@carlosdlr is this done or you are going to do more?

**Comment by carlosdlr** [comment]
Hello @Emily-Jiang yes this is done,  i already have assigned some refactor to continue improving our tests here [271](https://github.com/eclipse/microprofile-fault-tolerance/issues/271)
