### ISSUE TITLE
New TCK tests don't include beans.xml in deployment 

### ISSUE THREAD

**Issue by antoinesd** [eclipse/microprofile-fault-tolerance#405]
This issue is the same than #318 for new tests like https://github.com/eclipse/microprofile-fault-tolerance/blob/master/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallbackmethod/FallbackMethodPrivateTest.java

**Comment by Azquelt** [comment]
That class does have an empty beans.xml but it looks like I added the test bean to the outer war instead of the test jar.

**Comment by Azquelt** [comment]
I couldn't find any other occurrences of the same mistake and I've raised #406 to fix this one.

Are you seeing the same issue on any other tests?
