### ISSUE TITLE
Exception-handling in Fallback

### ISSUE THREAD

**Issue by mfrembs** [eclipse/microprofile-fault-tolerance#417]
Hi,

I have an issue with the @Fallback procedure. I cannot throw Exceptions even if I like to.

I implemented a MP-Rest-client with a ResponseExceptionMapper. The ResponseExceptionMapper throws "MyException" if the HTTP-status is >= 300. If the GET-request succeeds I get "MyPojo" filled with the provided information.

Now I want to make that call resilient. So I annotate the method with @Fallback. The problem I have is, that the fallback-method is getting also called when the client throws MyException. But this Exception should not be "catched" by the fallback-method. The fallback-method itself has no clue why it is called. That means I don't know if it is getting called because there was an connection-error or something like that, or it is getting called because of the "expected" MyException. Therefore I cannot rethrow MyException.

The other option is to use a FallbackHandler. Then I have to implement a handle-Method with an ExecutionContext. The ExecutionContext tells me which exception lead to calling the FallbackHandler. But I cannot rethrow the exception unless it is a RuntimeException.

Do I oversee here something? I would like to get a blacklist with exceptions when the fallback (method or handler) is not getting called. Or at least a handle-method which throws exception.

Is it possible to add this in a future version?

Thanks!

**Comment by Emily-Jiang** [comment]
@def456 Thanks for the use case! Based on your description, you would like to selectively trigger fallback. I think we could add a default method like
    ```
@Nonbinding
Class<? extends Throwable>[] abortOn() default {};
```
For your use case, you can build up a blacklist.

I think blacklist might be more useful than a whitelist. Thoughts?

**Comment by def456** [comment]
Thanks for your fast reply @Emily-Jiang . Yes, I also think a blacklist would be the right thing. I'm not sure about the name "abortOn()". It's a bit confusing. Will the fallback be aborted or will the fallback be called, when the underlying method is aborted by the named exceptions. I suggest "ignoreExceptions()" or something like that.

**Comment by def456** [comment]
By the way: I have the same issue with the CircuitBreaker. I can only define a whitelist (failOn) but not a blacklist. Should I create an extra issue for this use case?

**Comment by Emily-Jiang** [comment]
You can create an issue for discussion on CircuitBreaker as I am not sure whether it is a must to add it as yet.

**Comment by def456** [comment]
I'd prefer `skipOn()`. This sounds good to me.

Do you have a roadmap until when this could be a) in the microprofile spec. and b) in the wlp / olp?

**Comment by Emily-Jiang** [comment]
This should be in MP FT spec. I will try to come up with a PR soon.

**Comment by Emily-Jiang** [comment]
Based on today's hangout, we agreed that we would sync up with #418 and use the similar approach for Fallback.

**Comment by Emily-Jiang** [comment]
We (@michalszynkiewicz @Ladicek @Azquelt @carlosdlr and I) discussed on the call today. The consensus is to use Option 1 (blacklist wins over whitelist) and introduce a method and applyOn (whitelist), skipOn (blacklist) methods. @mfrembs please comment asap if you disagree.

**Comment by mfrembs** [comment]
Sounds good, thanks!
