### ISSUE TITLE
Exception-Handling in CircuitBreaker

### ISSUE THREAD

**Issue by mfrembs** [eclipse/microprofile-fault-tolerance#418]
Hi,

this is an extra issue for the same use-case I talked about here [1] but this time for the CircuitBreaker and not Fallback.
[1] https://github.com/eclipse/microprofile-fault-tolerance/issues/417

I implemented a MP-Rest-client with a ResponseExceptionMapper. The ResponseExceptionMapper throws "MyException" if the HTTP-status is >= 300. If the GET-request succeeds I get "MyPojo" filled with the provided information.

Now I want to make that call resilient. So I annotate the method with CircuitBreaker. The problem I have is, that the CircuitBreaker is getting also "activated" when the client throws MyException. But this Exception should not be "catched" by the CircuitBreaker. Right now there is only the possibility of a whitelist with "failOn".

Do I oversee here something? I would like to get a blacklist with exceptions when the CircuitBreaker is not getting activated.

Thanks!

**Comment by Emily-Jiang** [comment]
Are you just playing with the annotations or this is your real business scneario?

**Comment by Emily-Jiang** [comment]
We discussed today, we could add another method skipOn() . Here are some thoughts?
- failOn()
 and skipOn() have no overlapping - easy, use failOn

- failOn() and skipOn() overlap, 
failOn(MyException1.class, MyException2.class)
skipOn(MyException1.class) 
Should we join then or they are mutually exclusive?
Thoughts?

**Comment by def456** [comment]
Right now I am building a reference application for a customer. But this will be sooner or later become a real business scenario. I'm a bit confused that no one run into this issue before me ;-)

My first thought was: Why would you define a whitelist and a blacklist together. But my further thought was: that could make sense. Imagine the following use case:

Global "MyServiceException"
With following Exceptions inheriting: "MyConnectionException", "MyValidationException", "MyIOException".

Now I want to fail on MyServiceException (and therefor also on the other 3) but I want to skip on MyValidationException. So I would annotate it with `failOn = MyServiceException.class, skipOn = MyIOException.calls`. Can you follow me?

This way it would be more flexible and you should have every use case.

For my use case the easy one (mutually exclusive) would be sufficient, but I would recommend to do the more flexible option.

**Comment by michalszynkiewicz** [comment]
If we allow to have both, I think it should work as follows:
```java
class E0 extends Exception {...}

class E1 extends E0 {...}

class E2 extends E1 {..}

// skips CB for E2 and its subclasses, does it for all E1 and all other sub-classes:
@CircuitBreaker(failOn=E1.class, skipOn=E2.class) 

// performs the CB on E2 and its subclasses and does not on any other exceptions
// and E1 doesn't add anything here
@CircuitBreaker(failOn=E2.class, skipOn=E1.class) 

// performs the CB on E2 and its subclasses and on all E0 subclasses that are not E1 or E1's subclasses
@CircuitBreaker(failOn={E0.class, E2.class}, skipOn=E1.class) 
```

**Comment by Emily-Jiang** [comment]
@michalszynkiewicz 
If we want to support the scenario where you can specify both:
`@CircuitBreaker(failOn=A.class, skipOn=B.class) `

We need to remove skipOn and its subclass from the failOn bucket. This could end up with an empty set, which is fine, just meaning no circuit breaker defined.

In summary, the logic is to remove skipOn from failOn.

**Comment by Ladicek** [comment]
@michalszynkiewicz The last example of yours is particularly interesting, as `E2` is a subclass of `E1`. Who wins?

And what would happen in case of `@CircuitBreaker(failOn={Exception.class, E1.class}, skipOn={E0.class, E2.class})`?

In any case, I'd like this behavior to mirror the behavior of `@Retry`'s `retryOn` and `abortOn`, but unfortunately, the spec doesn't really define what would happen in case of `@Retry(retryOn={E0.class, E2.class}, abortOn=E1.class)`, so there's nothing to get inspiration from.

**Comment by michalszynkiewicz** [comment]
@Ladicek it would be all exceptions but E0 and subclasses that are not E1 subclasses and but E2 subclasses.

A simple, reasonable alternative could be to apply the `failOn` first and then apply `skipOn` not looking back at `failOn`.

This way my third example and yours would result in:
```
// performs the CB on all E0 subclasses that are not E1 or E1's subclasses
// and E2 doesn't matter here
@CircuitBreaker(failOn={E0.class, E2.class}, skipOn=E1.class) 

// performs CB on any exception but E0 and E0's subclasses
@CircuitBreaker(failOn={Exception.class, E1.class}, skipOn={E0.class, E2.class})
```

**Comment by Ladicek** [comment]
@michalszynkiewicz Sorry, I don't understand. Is this what you mean?

`@CircuitBreaker(failOn={E0.class, E2.class}, skipOn=E1.class)`

Exception thrown | Circuit breaker treats it as
------------ | -------------
`Exception` | success
`E0` | failure
`E1` | success
`E2` | failure
a subclass of `E2` | failure
a subclass of `E1` that isn't subclass of `E2` | success
a subclass of `E0` that isn't subclass of `E1` | failure
`RuntimeException` | success
`Throwable` | success

`@CircuitBreaker(failOn={Exception.class, E1.class}, skipOn={E0.class, E2.class})`

Exception thrown | Circuit breaker treats it as
------------ | -------------
`Exception` | failure
`E0` | success
`E1` | failure
`E2` | success
a subclass of `E2` | success
a subclass of `E1` that isn't subclass of `E2` | failure
a subclass of `E0` that isn't subclass of `E1` | success
`RuntimeException` | failure (subclass of `Exception`)
`Throwable` | success

I agree this makes sense, but how would the decision algorithm look like? I think you'd have to traverse the entire inheritance chain, from bottom to top, and for each class check if it's present in either of the two sets. Right? Something like:

```java
// pseudocode
boolean isSuccess(
    Set<Class<? extends Throwable>> failOn,
    Set<Class<? extends Throwable>> skipOn,
    Throwable thrown
) {
    Class<? extends Throwable> clazz = thrown.getClass();
    while (clazz != null) {
        if (failOn.contains(clazz)) {
            return false;
        } else if (skipOn.contains(clazz)) {
            return true;
        } else {
            clazz = clazz.getSuperclass();
        }
    }
    // TODO interfaces
    return true;
}
```

Is that what you mean? If so, we can debate how exactly interfaces implemented by the exception classes come into play, as in that case, there isn't an inheritance chain, but entire tree. Perhaps best to forbid including interfaces in `failOn` / `skipOn` :-)

**Comment by michalszynkiewicz** [comment]
Yes, this is what I meant originally.

By the simplified approach I meant:

`@CircuitBreaker(failOn={E0.class, E2.class}, skipOn=E1.class)`

Exception thrown | Circuit breaker treats it as
------------ | -------------
`Exception` | success
`E0` | failure
`E1` | success
`E2` | success
a subclass of `E2` | success
a subclass of `E1` that isn't subclass of `E2` | success
a subclass of `E0` that isn't subclass of `E1` | failure
`RuntimeException` | success
`Throwable` | success

`@CircuitBreaker(failOn={Exception.class, E1.class}, skipOn={E0.class, E2.class})`

Exception thrown | Circuit breaker treats it as
------------ | -------------
`Exception` | failure
`E0` | success
`E1` | success
`E2` | success
a subclass of `E2` | success
a subclass of `E1` that isn't subclass of `E2` | success
a subclass of `E0` that isn't subclass of `E1` | success
`RuntimeException` | failure (subclass of `Exception`)
`Throwable` | success


The algorithm for it should be much simpler to implement but it wouldn't be that intuitive.

**Comment by Ladicek** [comment]
I agree the more complex variant is more intuitive, and I'd personally be fine with using it. Question is:

1. What about interfaces?
2. How to specify it? Using a pseudocode with a few examples of expected outcomes, like I did above?
3. How do existing implementations handle the `retryOn` / `abortOn` attributes of `@Retry`? I believe it should use the same algorithm. It's currently underspecified, so existing implementations might differ already. I believe this should be portable and therefore defined in detail in the spec.

**Comment by michalszynkiewicz** [comment]
I have mixed feelings on interfaces.
On one side, I think we could go with such limitation. On the other, it seems to be a nice way of marking exceptions "failable" or "abortable". With interfaces one wouldn't have to create strange class hierarchies or long lists of exceptions in the annotation.

The plus side of the simplified approach is that the interfaces don't hurt us.

@Emily-Jiang, what do you think?

**Comment by michalszynkiewicz** [comment]
re 2, I like the tables. Maybe another column to explain why it works that way could be beneficial
re 3, I don't know how `@Retry` does it now

**Comment by Emily-Jiang** [comment]
@brunobat will investigate how Retry works when specifying both retryOn and abortOn in tck and make Retry, CircuitBreaker to be consistent.

**Comment by RobWin** [comment]
We have an implementation for this in Resilience4j, if you would like to have a look at it.

**Comment by mfrembs** [comment]
What is the current state?

**Comment by Emily-Jiang** [comment]
At today's hangout, we discussed this further. @carlosdlr will take a look at the tck to see what is the current behaviour and then come back to discuss again in the next couple of weeks to see which approach we should proceed with.

**Comment by carlosdlr** [comment]
Hello,
Adding a few tests to see current behavior in the `@Retry` annotation using whitelist(retryOn) and blacklist(abortOn) at these scenarios

1. Using inheritance at exception class level (configuring in the "retry on" list the parent exception class but throwing a child exception).

Findings: Is executing the retry policy due is recognizing that the exception that is throwing the service is a child class.

2. Using both lists retryOn and abortOn (configuring in the retryOn list the parent exception class and in the obortOn list the child exception class that is thrown by the service).

Findings: Is not executing the retry policy due in this case the obortOn has higher precedence because the type is the same that is thrown by the service so not takes into account the parent exception class that is configured in the retryOn list.

With this, we can have at a started point to see basic behaviors using whitelist and blacklist in the same spec in this case retry (that is already implemented in openliberty)  and try to be consistent if we will add this to other specs like fallback and circuit breaker

I'll add more test cases taking the scenarios described here in this issue, we can use this pull request https://github.com/eclipse/microprofile-fault-tolerance/pull/437 to discuss and suggests more tests.

**Comment by Ladicek** [comment]
#437 looks like a good start, but we certainly need to verify the more complex cases. It might already be the case that various implementation differ. I'll try to put something together and send a PR to your PR :-)

**Comment by Ladicek** [comment]
In the end, I added my tests as a separate PR: https://github.com/eclipse/microprofile-fault-tolerance/pull/440

If someone could run that test with OpenLiberty, that would be great. It currently passes on SmallRye Fault Tolerance, but I expect that it will fail elsewhere, which would be a good opportunity to actually specify the expected behavior.

**Comment by Emily-Jiang** [comment]
@michalszynkiewicz at today's hangout, @Ladicek @Azquelt @carlosdlr and I discussed the behaviour of whitelist (`retryOn`) and blacklist (`abortOn`). The current logic is that blacklist has higher priority than whitelist. It does make sense. How about make this rule across the board e.g. applying to `CircuitBreaker`, `Fallback`?

**Comment by Ladicek** [comment]
Also adding @mfrembs as the original poster.

**Comment by Emily-Jiang** [comment]
@mfrembs @michalszynkiewicz will you be able to join next week Tuesday 2-3pm UK time?

**Comment by Azquelt** [comment]
So, we have two suggested behaviours:
1) Blacklist (`abortOn`) has higher priority than whitelist (`retryOn`)
2) Closest superclass included in either list decides the result

As far as I can see, the advantages of option 1:
* Maintains existing behaviour of smallrye and openliberty
* It's simple to explain and specify
* Simple to implement

Advantages of option 2:
* Allows user to blacklist a class and then whitelist a subclass
* More intuitive
* No cases where the user can specify something that is redundant. e.g.  
`@Retry(abortOn=E0.class, retryOn=E1.class)` (for option 1, `retryOn=E1.class` has no effect)

**Comment by Ladicek** [comment]
For option 2, there's one case where you can specify redundant stuff: `@Retry(abortOn=E0.class, retryOn=E0.class)` :-) I don't know why anyone would do that, but something would have to have a higher priority anyway.

**Comment by Emily-Jiang** [comment]
We (@michalszynkiewicz @Ladicek @Azquelt @carlosdlr and I) discussed on the call today. The consensus is to use Option 1 and introduce a method skipOn method. @mfrembs please comment asap if you disagree.

**Comment by mfrembs** [comment]
Sorry for the late reply, I'm just returning from my summer vacation. Option 1 sounds good for me, it will solve my issue. Thanks for finding a solution and integrating me. I would have joined your phone call if I would have had time.
