### ISSUE TITLE
need clarification on CircuitBreaker.failOn + metrics

### ISSUE THREAD

**Issue by Ladicek** [eclipse/microprofile-fault-tolerance#419]
If I have a `@CircuitBreaker(failOn = {IllegalArgumentException.class})` method and e.g. `IllegalStateException` is thrown, which circuit breaker metric should be incremented?

The MP Fault Tolerance spec is a little vague in this regard:

1. `circuitbreaker.callsSucceeded.total` is defined as "Number of calls allowed to run by the circuit breaker that returned successfully"
1. `circuitbreaker.callsFailed.total` is defined as "Number of calls allowed to run by the circuit breaker that then failed"
1. the `@CircuitBreaker` javadoc says "A method call will be considered a failure if it throws an exception and the type of that exception is assignable to any of the types listed in `failOn`."

From item 1 follows that in case of any exception, it should be the `circuitbreaker.callsFailed.total` metric that is incremented, because throwing an exception isn't a "successful return". However, from items 2+3 follows that it should be `circuitbreaker.callsSucceeded.total`.

The TCK doesn't have a test for this.

My opinion is that the 2nd interpretation is correct, because that's how everything else in the circuit breaker works. WDYT?

**Comment by Ladicek** [comment]
I'd be happy to submit a PR for my 2nd interpretation (hopefully I'd manage to add a test to the TCK as well :-) ).

I believe it would be enough to change the wording in the "Metrics added for `@CircuitBreaker`" chapter of the spec like this:

1. Define `circuitbreaker.callsSucceeded.total` as "Number of calls allowed to run by the circuit breaker that wasn't considered a failure by the circuit breaker".
1. Define `circuitbreaker.callsFailed.total` as "Number of calls allowed to run by the circuit breaker that was considered a failure by the circuit breaker".
1. No other change. (Perhaps both items above could mention the `failOn` parameter, but I don't consider that necessary.)

WDYT?

**Comment by Emily-Jiang** [comment]
I am a bit confused with your suggestion though. If the exception does not match fallOn, from circuit breaker metrics point of view, it is a success.

**Comment by Ladicek** [comment]
> If the exception does not match fallOn, from circuit breaker metrics point of view, it is a success.

That's exactly what I'd like the specification to say. It currently doesn't, in my opinion.

**Comment by Azquelt** [comment]
I agree that your second interpretation is the correct one, I'd welcome a PR that improved the wording in the spec. Adding a test for this to `CircuitBreakerMetricTest` would be great too.

**Comment by Emily-Jiang** [comment]
@Ladicek  will do a PR to clarify this and add a test.

**Comment by Emily-Jiang** [comment]
@brunobat will investigate how Retry works when specifying both retryOn and abortOn in tck and make Retry, CircuitBreaker to be consistent.
