### ISSUE TITLE
Prepare spec to support Java 11

### ISSUE THREAD

**Issue by brunobat** [eclipse/microprofile-fault-tolerance#423]
We depend on other specs and will not be fully compliant until CDI, config and metrics move on that direction. 
However, we should make sure that all the code used in the FT spec is Java 11 friendly as far as possible.

**Comment by Azquelt** [comment]
To do this we should:
 - Ensure the code can be compiled with Java 11 (it doesn't at the moment)
 - Check we are not relying on anything that has been removed from the standard library

**Comment by Emily-Jiang** [comment]
I will bring up in MicroProfile google group to discuss the support for Java 11 so that all specs are in the position to compile and run on Java 11.

**Comment by kenfinnigan** [comment]
See https://github.com/eclipse/microprofile/issues/106, there are various levels of JDK 11 support.

Please update https://wiki.eclipse.org/MicroProfile/JDK11Runtime with information about FT

**Comment by brunobat** [comment]
Will run some experiments with Java 11. Might be useful to run the build against newer versions on the java jdk to evaluate compliance.
