### ISSUE TITLE
Improve spec on use of threads for retry and asynchronous

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-fault-tolerance#424]
7.1 says
> If `@Retry` is used with `@Asynchronous` and a retry is required, the new retry attempt may be run on the same thread as the previous attempt, or on a different thread.

This suggests that doing all retries on the same thread is a valid strategy.

However, 6.1 says
> If `@Timeout` is used with `@Retry`, a `TimeoutException` may trigger a retry, depending on the values of `retryOn` and `abortOn` of the `@Retry` annotation. The timeout is restarted for each retry. If `@Asynchronous` is also used and the retry is the result of a `TimeoutException`, the retry starts after any delay period, even if the original attempt is still running.

This effectively precludes doing all retries on the same thread in cases where a `TimeoutException` occurs.

@jbee pointed out that it's unhelpful to suggest that either strategy is valid in one part of the spec and then invalidate one of those strategies in another part.

**Comment by kenfinnigan** [comment]
Ideally, all references to anything happen on specific threads should be removed from the spec

**Comment by Azquelt** [comment]
Perhaps, but let's keep that discussion in its own issue

**Comment by kenfinnigan** [comment]
Isn't it easier to tackle all mentions of threads in one pass?

**Comment by Azquelt** [comment]
If we were going to remove all mentions of threads, then yes, we would do that in one pass.

However, unless that's agreed and started, I'd like to fix the way the current spec is described. I'm not suggesting changing any of the semantics here, just pointing out that the way 7.1 is currently written is misleading and unhelpful in view of what's stated in 6.1.
