### ISSUE TITLE
Implementation of Future should be transparent

### ISSUE THREAD

**Issue by jbee** [eclipse/microprofile-fault-tolerance#425]
Some tests (e.g. `org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadFutureTest.testBulkheadClassAsynchFutureDoneAfterGet`) make the assumption that a `Future` returned from a method with FT behaviour does delegate to the original future instance returned by the wrapped method which is observable by `get()` and `get(long timeout, TimeUnit unit)` actually returning different values.

Delegation as solution is also asked for in the spec:

> If the execution completes normally and returns a value, the Future or CompletionStage will then delegate to the returned value.

This is only one way to implement it but since the result of `get` with or without timeout should be consistent any other solution that behaves correctly should be valid. After all this is the point of using abstractions.

**Comment by jbee** [comment]
See PR #426

**Comment by Ladicek** [comment]
I'm working on an alternative pull request. Work in progress draft here: #471.

**Comment by jbee** [comment]
Thanks @Ladicek
