### ISSUE TITLE
File 0004-FaultTolerance.md is missing

### ISSUE THREAD

**Issue by lutzhorn** [eclipse/microprofile-fault-tolerance#427]
The file `File 0004-FaultTolerance.md` mentioned in the `README.adoc` is missing.

https://github.com/eclipse/microprofile-fault-tolerance/blob/1af5205f7bb7c90d4f953885e1eaf9c2fbea300f/README.adoc#L23

**Comment by Azquelt** [comment]
I've rewritten the readme and it no longer references the missing file.
