### ISSUE TITLE
Allow for config [Spec Class] properties to be prefixed with mp.ft?

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-fault-tolerance#435]
Currently we support properties like

Retry/maxRetries=30

Do we want to also accept the following as an equivalent (with precedance)

mp.ft.Retry/maxRetries=30

I would go further and say that, as we know what the prefix of valid classes
is that begin mp.ft (i.e the defaults across all user classes ones) we can use:

mp.ft.Retry.maxRetries=30

and therefore make them look like the more recent MicroProfile spec's config
parameters?

I am attempting to resolve https://github.com/eclipse/microprofile/pull/100

**Comment by Emily-Jiang** [comment]
Thinking about the confusion it will introduce to the end users without much gain. I think it makes more sense to use some guideline for new properties but leaving the existing properties as they are.

**Comment by Emily-Jiang** [comment]
Not going to update the config names.
