### ISSUE TITLE
Bug in TCK tests validating MP_Fault_Tolerance_NonFallback_Enabled

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-fault-tolerance#451]
`DisableFTEnableGloballyTest`, `DisableFTEnableOnClassTest`, and `DisableFTEnableOnMethodTest` all attempt to set two different assets into the Shrinkwrap archive for `microprofile-config.properties` which results in only the setting to disable FT being present within `microprofile-config.properties` of the Arquillian deployment, and it doesn't include the config enabling settings.

**Comment by Emily-Jiang** [comment]
I don't quite understand what you meant by saying:

> nd it doesn't include the config enabling settings.

As for disabling the FT annotation globally, specifying the following in the file of microprofile-config.property should be enough:

> .addAsManifestResource(new StringAsset("MP_Fault_Tolerance_NonFallback_Enabled=false"),
                    "microprofile-config.properties")
In the Fault Tolerance spec, it states clearly on the dependency of MicroProfile Config.

**Comment by kenfinnigan** [comment]
As can be seen in the PR (https://github.com/eclipse/microprofile-fault-tolerance/pull/452/files), previously three tests set the `MP_Fault_Tolerance_NonFallback_Enabled` property as the value for `microprofile-config.properties` and then set the value of the config overrides into the same file.

As a result, Shrinkwrap ignored the setting of the overrides as there was already a node present for `microprofile-config.properties`.

**Comment by Emily-Jiang** [comment]
ah. It makes sense now. Thanks @kenfinnigan ! The PR looks good.
