### ISSUE TITLE
TCK fails with latest Metrics

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-fault-tolerance#464]
Tried running MP FT with latest MP Metrics in SmallRye, and the TCK fails because of a change to MP Metrics where `Gauge` was changed to extend `Number`.

Though it's only impacting the MP FT TCK right now, I'm not sure if that's a "problem" for MP 3.1 or not?

**Comment by kenfinnigan** [comment]
Metrics should probably support the old method, otherwise it probably needed to be Metrics 3.0

Right now I'm concerned that anyone using MP 3.1 will be broken

**Comment by Azquelt** [comment]
This looks like anyone with an application which uses the `Gauge` interface directly is probably broken on MP 3.1 since effectively the old method has been removed and a new one added :(

That's probably _fairly_ uncommon, since usually you'd use `@Gauge` to register a gauge and you wouldn't inspect the metric within your own application.

**Comment by kenfinnigan** [comment]
Maybe, but I know the spec says you can inject and register metrics through the SPI, which would definitely break.

I've sent an email to the MP ML raising the problem to see what possible options we have

**Comment by Emily-Jiang** [comment]
I put the plugin for semantic version for spotting breaking changes. However, for some reason, the baseline was removed by someone. Therefore, this is unguarded. We must enforce all specs to use the semantic versioning plugin to police the API changes.

**Comment by Ladicek** [comment]
If I understand correctly, this is "just" a binary incompatible change, and rebuilding the MP FT TCK against MP Metrics 2.1 would fix the problem. (Upper bound of the type parameter changed, which means that, even after erasure, signatures of methods that use the type parameter also changed. Which leads to linkage error.)

I'm not sure if that's considered a breaking change in MP. It probably should, though spotting binary incompatible changes can be quite hard.

**Comment by kenfinnigan** [comment]
If it's only a binary incompatible change that's not too bad, but I think it would necessitate an MP FT 2.1 being added to MP 3.1 to align them.

After lunch I will try updating MP FT and building downstream projects to see if it is just a binary incompatibility

As you say though, not sure how to prevent these issues going forward.

**Comment by kenfinnigan** [comment]
If I update the 2.0.x branch to use MP Metrics 2.1.0 in the TCK and then build SmallRye Fault Tolerance with a dependency on MP FT 2.0.3-SNAPSHOT the TCKs pass.

So it's confirmed it's just a binary incompatibility.

Do we need to update MP FT and do a 2.0.3?

**Comment by kenfinnigan** [comment]
In what way wouldn't it work? I just ran it and it passed

But I agree it shouldn't be something MP FT has to "work around"

**Comment by donbourne** [comment]
I think the only way we'd avoid this issue is to reverse the change that made Gauges be required to be Numeric.  @Ladicek  I don't see what you mean about having a bridge method with Object return type -- could you show a code sample of that you're thinking there?  Given we would need to change Gauges to have getValue return Object we wouldn't also be able to have Gauges with getValue returning Number.

**Comment by Ladicek** [comment]
@donbourne Yeah, it's not possible to express that in Java source code, as Java the language doesn't permit overloading based solely on return type. The JVM bytecode, on the other hand, does. So my suggestion would rightfully be classified as trickery; I would still say it's a valid option.

**Comment by jmartisk** [comment]
Hm, could we have one MP FT TCK 2.0.x release compiled against Metrics 2.0 and one compiled against Metrics 2.1? 
And distinguish between them using Maven qualifiers, or something? 
If that solution is too clunky we could back this change out in Metrics 2.1.1.

**Comment by Azquelt** [comment]
It's not something that the FT TCK should have to work around, but unless there's a new version of MP Metrics which fixes the binary incompatibility, I think we probably should work around it. We already have some reflection in the TCK to allow it to run against Metrics 2.0 and 2.1.

@jmartisk If you back out the change in Metrics 2.1.1, you'll break binary compatibility with Metrics 2.1.0.

**Comment by Azquelt** [comment]
@Ladicek I also thought about whether you could have a bridge method!

The only way I could see it being done without modifying the bytecode after compilation would be to extend another interface with the old signature, which would look a bit odd in the API.

```
public interface Gauge<T extends number> extends GagueCompat<T> {
    public T getValue();
}

public interface GaugeCompat<T> {
    public T getValue();
}
```

**Comment by jmartisk** [comment]
I am aware we would break compat with Metrics 2.1.0 but I would say that's much less of a problem than we have today, especially given that Metrics 2.1.0 is brand new and probably isn't used much yet (not in production at least).

**Comment by donbourne** [comment]
I agree with @jmartisk -- I suggest we quickly put out an errata and a Metrics 2.1.1 that puts back the old return type for Gauges.

**Comment by Emily-Jiang** [comment]
Close this one as Metrics 2.2 was released to undo the changes.
