### ISSUE TITLE
Update to Jakarta EE8 APIs for MP 4.0 in Jun 2020

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-fault-tolerance#467]

**Comment by kenfinnigan** [comment]
Re-opening as it was decided to push Jakarta EE 8 API to MP 4.0

**Comment by Ladicek** [comment]
Do we revert from MP FT 2.1? Do we push MP FT 2.1 to MP 4.0? (And possibly make it MP FT 3.0?)

**Comment by kenfinnigan** [comment]
That's up to MP FT as to whether there's anything wanted in MP 3.3, and whether you want a breaking change release in June

**Comment by Ladicek** [comment]
Sure, that question was directed at the MP FT fellows :-)

**Comment by kenfinnigan** [comment]
sorry, will stick my nose out now
