### ISSUE TITLE
specify lifecycle of the circuit breaker

### ISSUE THREAD

**Issue by Ladicek** [eclipse/microprofile-fault-tolerance#479]
Circuit breaker maintains state over time, between various invocations of the guarded method. Therefore, the circuit breaker object needs to have a lifecycle. For example, in SmallRye Fault Tolerance, all circuit breakers are singletons -- no matter the scope of a bean (be it `@Dependent` or `@RequestScoped`), all invocations of a single method are guarded by the same circuit breaker instance.

https://github.com/eclipse/microprofile-fault-tolerance/issues/302 suggests that the circuit breaker should follow the lifecycle of the bean, but to the best of my knowledge, this isn't specified. There are no tests for it in the TCK either.

I only found out because the new `CircuitBreakerExceptionHierarchyTest` test relies on that behavior.

**Comment by Ladicek** [comment]
I'd also like to point out that both possibilities (following the lifecycle of the bean, and following the lifecycle of the class = singleton) make sense and have usecases. For example, say I have a `@RequestScoped` bean that invokes an external service and I want to guard invocations to that external service by a circuit breaker. In such case, I want the circuit breaker to _not_ follow the lifecycle of the bean -- all instances of the `@RequestScoped` bean should share the same circuit breaker. One might argue that in such case, invocations to that external service should be centralized into an `@ApplicationScoped` bean, but that isn't exactly user-friendly.

**Comment by Ladicek** [comment]
Also if the metrics _isn't_ a singleton, then metrics like "amount of time the circuit breaker has spent in open state" don't make sense.

**Comment by Azquelt** [comment]
One argument in favour of tying it to the object lifecycle is that it's implemented as an interceptor and the lifecycle of an interceptor is the same as the object it intercepts.

**Comment by michalszynkiewicz** [comment]
As it is a CircuitBreaker for the underlying call, I think the state should rather be application wide (in other words, a singleton).
The only use case for having it tied to a scope bean is when each bean instance would contact a different service. Can you think of any other use cases?

**Comment by Emily-Jiang** [comment]
I agree that it is not usable for the `RequestScoped` Bean to have `CircuitBreaker` if the `CircuitBreaker` is bound to the lifecycle of the instance. There are two suggestions:

1. Only allow CircuitBreaker to apply on ApplicationScoped bean. Otherwise, a warning or an error will be thrown.

1. Allow CircuitBreaker to apply on any beans. Implementation should ignore the lifecycle of the bean but treating as a static variable.
I agree that we need to apply the similar pattern to 'Bulkhead' as suggested by @Azquelt

**Comment by Azquelt** [comment]
Is this sort of thing an issue:

```java

public abstract class AbstractService() {

    @CircuitBreaker
    public Result callService() {
        return new Request(getServiceUrl()).get("/theService");
    }

    protected abstract String getServiceUrl();
}


public class ServiceA extends AbstractService {
    public String getServiceUrl() {
        return "http://blah/";
    }
}

public class ServiceB extends AbstractService {
    public String getServiceUrl() {
        return "http://wibble/";
    }
}
```

**Comment by Ladicek** [comment]
Here's a bit of a counterpoint where it would make more sense for subclasses to share the circuit breaker:

```java
public abstract class AbstractService {
    @CircuitBreaker
    public Result callService() {
        Response response = Request.Get("http://my-service/").execute();
        return process(response);
    }

    // template method
    protected abstract Result process(Response response);
}

public class ServiceA extends AbstractService {
    public String process(Response response) {
        return doSomethingWith(response);
    }
}

public class ServiceB extends AbstractService {
    public String process(Response response) {
        return doSomethingElseWith(response);
    }
}
```

I'm aware that it mixes submitting a request and processing a response. I think I'd be fine if each subclass had its own circuit breaker.

**Comment by Emily-Jiang** [comment]
Specify the lifecycle for both `CircuitBreaker` and `Bulkhead` as one per class instead of one per instance.

**Comment by Ladicek** [comment]
Submitted a draft spec proposal here: https://github.com/eclipse/microprofile-fault-tolerance/pull/525
