### ISSUE TITLE
Timeout for concurrent execution tracker should be configurable

### ISSUE THREAD

**Issue by Joseph-Cass** [eclipse/microprofile-fault-tolerance#510]
Currently, in [ConcurrentExecutionTracker.java](https://github.com/eclipse/microprofile-fault-tolerance/blob/master/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/util/ConcurrentExecutionTracker.java) `WAIT_TIMEOUT` is set to `3L * 1000 * 1_000_000`.

This means that anywhere that uses `waitForRunningExecutions()` waits for up to 3 seconds.

This class is used by some tests which have configurable timeouts, e.g. [BulkheadMetricTest.java](https://github.com/eclipse/microprofile-fault-tolerance/blob/master/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricTest.java). Can we configure this timeout as well so that it is adjusted in line with the rest of the test?

**Comment by Joseph-Cass** [comment]
I have linked a PR with a potential solution

**Comment by Azquelt** [comment]
I think this makes sense. `waitForRunningExecutions()` is just waiting for async tasks to start. 3 seconds is pretty arbitrary and should generally be long enough but if we're scaling the timeouts because the CI system is unreliable, this looks like a good candidate to be scaled.
