### ISSUE TITLE
specification for @Asynchronous assumes existence of security/naming context

### ISSUE THREAD

**Issue by Ladicek** [eclipse/microprofile-fault-tolerance#514]
The very beginning of the specification text for `@Asynchronous` says:

> `Asynchronous` means the execution of the client request will be on a separate thread.
> This thread should have the correct security context or naming context associated with it.

However, MicroProfile doesn't know anything about security context or naming context. These are purely EE concerns.

We should separate that sentence into a dedicated section somewhere near the end of the specification, similarly to other MP specifications that also deal with EE concerns (such as MP JWT: https://download.eclipse.org/microprofile/microprofile-jwt-auth-1.1.1/microprofile-jwt-auth-spec.html#_recommendations_for_optional_container_integration). Also, we should make the sentence more concrete. Something like:

> ## Recommendations for Optional Container Integration
>
> This section describes the expected behaviors when the implementation runs in a Java EE container.
>
> ### Asynchronous
>
> Threads that are servicing `@Asynchronous` invocations should, for the duration of the invocation, have the correct security context and naming context associated.

**Comment by Ladicek** [comment]
We should also add some TCK tests for this, in an optional way.

**Comment by Emily-Jiang** [comment]
related to #326

**Comment by Ladicek** [comment]
Submitted a PR. I didn't add a TCK test, because 1. it would have to be a separate TCK module, 2. even if I did that, I don't know how I would test this :-)
