### ISSUE TITLE
Timeout value for metrics.AllMetricsBean should be configurable

### ISSUE THREAD

**Issue by Joseph-Cass** [eclipse/microprofile-fault-tolerance#519]
[AllMetricsTest](https://github.com/eclipse/microprofile-fault-tolerance/blob/master/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsTest.java) uses  [AllMetricsBean](https://github.com/eclipse/microprofile-fault-tolerance/blob/master/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsBean.java) to test `that metrics are created when all the Fault Tolerance annotations are placed on the same method`.

This bean has a Timeout value of 1 second, which is irrelevant to the test.

This value should be configurable.

**Comment by Ladicek** [comment]
Given that the timeout in that test is supposed to never occur, would it be best to just raise that value to 1 minute and be done with it? :-)

**Comment by Joseph-Cass** [comment]
That's certainly a more simple solution to the problem :) I'm happy with that if others are

**Comment by Azquelt** [comment]
Increasing the timeout makes sense and makes it clearer that the timeout should never be hit, so let's definitely do that.

I think I'd prefer to also add the multiplier in case we end up extending this test in the future. The `autoscaleMethod` would also scale a bunch of other values in addition to the timeout length.

**Comment by Emily-Jiang** [comment]
Is the timeout used at all? If not, just delete it. Otherwise, making it configurable is good.

**Comment by Azquelt** [comment]
The method call should never time out, but the `@Timeout` annotation is important for the test because we're checking that the correct metrics are generated when all the Fault Tolerance annotations are present.

**Comment by Joseph-Cass** [comment]
I have made a PR with a potential solution to this problem
