### ISSUE TITLE
Revisit return type for @Asynchronous

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-fault-tolerance#550]
In the javadoc on `@Asynchronous`, it states:

> The return type {@link java.util.concurrent.CompletionStage} is preferred over {@link java.util.concurrent.Future}
>  * as a {@link java.util.concurrent.Future} that completes exceptionally will not trigger other Fault Tolerance operations 
>  * even if specified (e.g. Retry), while a {@link java.util.concurrent.CompletionStage} that completes exceptionally will trigger other 
>  * Fault Tolerance capabilities if specified (e.g. Retry).

Should we use FT 3.0 to remove Future as the return type due to the above shortcomings?

**Comment by Ladicek** [comment]
I agree.

**Comment by Azquelt** [comment]
Returning a `Future` definitely has downsides compared to `CompletionStage` - it really only makes sense if you do a synchronous operation and then return a completed `Future` from your method - but I'm not sure about removing it.

It serves as a good replacement for `ExecutionService.submit(Callable)` which supports fault tolerance.

I also think that `Future` is more intuitive to use than `CompletionStage` although it's less powerful.

Do we have any guidelines around deprecating features before removing them from Microprofile?

**Comment by Emily-Jiang** [comment]
In light of the conversation and the impact, let's keep it and promote CS instead.
