### ISSUE TITLE
Fallback applyOn with Kotlin

### ISSUE THREAD

**Issue by Claxtastic** [eclipse/microprofile-fault-tolerance#588]
When I use the applyOn parameter for @Fallback in Kotlin:
`@Fallback(fallbackMethod = "fallbackSaveCallEventBatch", applyOn = { SQLException::class })`

I get two errors: 
`Annotation argument must be compile-time constant.`
`Type mismatch: inferred type is () -> KClass<SQLException> but Array<KClass<out Throwable!>> was expected.`

Is there a correct way to do this in Kotlin, or would something have to be fixed?

**Comment by Azquelt** [comment]
The error makes it look like it's complaining that it's getting a lambda when it's expecting an array. I'm not too familiar with Kotlin, but this doc section [Arrays as annotation parameters](https://kotlinlang.org/docs/reference/annotations.html#arrays-as-annotation-parameters) suggests that the syntax should be:

Kotlin 1.2+
```
@Fallback(fallbackMethod = "fallbackSaveCallEventBatch", applyOn = [ SQLException::class ])
```

Older versions
```
@Fallback(fallbackMethod = "fallbackSaveCallEventBatch", applyOn = arrayOf(SQLException::class))
```

**Comment by Claxtastic** [comment]
> The error makes it look like it's complaining that it's getting a lambda when it's expecting an array. I'm not too familiar with Kotlin, but this doc section [Arrays as annotation parameters](https://kotlinlang.org/docs/reference/annotations.html#arrays-as-annotation-parameters) suggests that the syntax should be:
> 
> Kotlin 1.2+
> 
> ```
> @Fallback(fallbackMethod = "fallbackSaveCallEventBatch", applyOn = [ SQLException::class ])
> ```
> 
> Older versions
> 
> ```
> @Fallback(fallbackMethod = "fallbackSaveCallEventBatch", applyOn = arrayOf(SQLException::class))
> ```

Oh perfect, that works. Thanks for clearing that up.

**Comment by Azquelt** [comment]
Happy to hear that :smiley:
