### ISSUE TITLE
CircuitBreaker failureRatio not working in Quarkus

### ISSUE THREAD

**Issue by Claxtastic** [eclipse/microprofile-fault-tolerance#589]
I have a Quarkus web service that has a class level CircuitBreaker annotation. In my application.properties, I have specified the properties for the CircuitBreaker:

`
com.example.reporting.webservice.service.DbCircuitBreakerService/CircuitBreaker/requestVolumeThreshold=8
com.example.reporting.webservice.service.DbCircuitBreakerService/CircuitBreaker/failureRatio=0.5
com.example.reporting.webservice.service.DbCircuitBreakerService/CircuitBreaker/delay=8000
com.example.reporting.webservice.service.DbCircuitBreakerService/CircuitBreaker/successThreshold=2
com.example.reporting.webservice.service.DbCircuitBreakerService/CircuitBreaker/unit=MILLIS
`

Here is the relevant class:

```
@ApplicationScoped
@CircuitBreaker
class DbCircuitBreakerService {

    private val log: Logger = LoggerFactory.getLogger(DbCircuitBreakerService::class.java)

    @Fallback(fallbackMethod = "fallbackSaveCallEventBatch")
    fun attemptSavePrimaryBatch(batch: CallEventsBatch, dao: ReportingDAO) {
        EntityManagerResolver.currentDatasourceName = "primary"
        dao.saveBatch(batch)
        log.info("saved call events batch in primary database")
    }

    private fun fallbackSaveCallEventBatch(batch: CallEventsBatch, dao: ReportingDAO) {
        EntityManagerResolver.currentDatasourceName = "secondary"
        dao.saveBatch(batch)
        log.info("saved call events batch in secondary database")
    }
}
```

There are several other primary and fallback methods to handle other scenarios.

The CircuitBreaker is registered and working; if I make a change to requestVolumeThreshold or delay for example, the change takes effect. But the failureRatio does not seem to be working correctly. The circuit is only opened on requestVolumeThreshold - 1. So, if the requestVolumeThreshold is 8, on the 7th failure it will finally open the circuit, even though I have the failureRatio of 50%. 

Is something with my configuration wrong, or is this a bug?

Thanks

**Comment by Emily-Jiang** [comment]
@Claxtastic there is a requestVolumeThreadshold is a rolling window, which means the circuit status will only be changed when the window is full. The window is rolling window. It will be reset once the circuit is opened and back to close again. In summary, the circuit breaker status will not be updated before a rolling window is full. Therefore, what you have observed is correct. However, once the window is full, you will get circuit breaker check on every followon request.

**Comment by Claxtastic** [comment]
@Emily-Jiang okay, interesting. Thank you for clearing that up. I was believe I was misled mainly by this passage in a Quarkus ebook I was reading: 

> if, within the last four invocations (requestVolumeThreshold) , 50% failed (
failureRatio), then the circuit transits to an open state. The circuit will stay open for 2,000 ms (
delay). After 2 consecutive successful invocations (successThreshold), the circuit will be back to close
again

Where then does the `failureRatio` come into play?

**Comment by Emily-Jiang** [comment]
Once you have the full rolling window, the `failureRation` will be used to judge whether the circuit should be opened or not.

**Comment by Ladicek** [comment]
I've also explaind this to @Claxtastic in the SmallRye Gitter. I think this issue can be closed.

**Comment by Claxtastic** [comment]
Yes sorry, thank you both for the explanations!
