### ISSUE TITLE
Istio Integration - overwrite Istio's retry and timeout

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-fault-tolerance#59]
[Istio Integration discussion](https://groups.google.com/forum/#!searchin/microprofile/Istio%7Csort:relevance/microprofile/O8qqDFCtsFo/oi1QdMHRBAAJ) 

[Istio Timeout and Retry](https://istio.io/docs/concepts/traffic-management/rules-configuration.html#timeouts-and-retries)

When MP FT works with Istio, Timeout and Retry are two problematic area. At the moment, the most restrictive Timeout will be honoured. As for Retry, if MP FT maxRetries =3 and Istio says 5, the app will retry 15 times.
In order to fix the conflicting area, we need to provide a way just to switch off Istio's timeout and retries.

Istio provides two special http headers “x-envoy-upstream-rq-timeout-ms” and “x-envoy-max-retries”. If the runtime e.g. Liberty, Wildfly swarm detects MP FT present and then put the http header on the request with the value of 0. In this way, it can turn off Istio's timeout and max retries while keeping the rest Istio's FT capabilities.

One possible solution is to ask app to set the headers, which is not clean as the app has no idea it will run in Istio. The better solution will be MP FT runtime set the headers when it detects Istio env. This might be achieved via HttpFilter or ClientRequestFilter.

**Comment by kenfinnigan** [comment]
Wouldn't it be better to go with Istio for retry and timeouts than disabling it?

MP FT should work with Istio and integrate with it rather than take over

**Comment by Emily-Jiang** [comment]
There are two options: #58 is to let Istio take over. This one is let app take over.

**Comment by kenfinnigan** [comment]
What would be the use case for letting the application take over something provided by Infrastructure and Ops?

I can see an application wanting to provide different configuration settings to Istio for retry and timeout, but not to "take over" handling of them.

**Comment by johnament** [comment]
We spoke about these integrations on the call yesterday.  @kenfinnigan  want to get your opinion about what we came up with.

Instead of us trying to deal with istio, shouldn't istio try to implement the MP Fault Tolerance API as a part of its offering?  That seems more appropriate from an integration POV.

**Comment by Emily-Jiang** [comment]
@kenfinnigan #48 provides a way for Istio to take over. In order to make MP FT working with Istio together, either MP FT retry/Timeout or Istio retry/timeout should be switched off. I do agree it should cover most of the cases. This is to provide a way to make App FT takeover. Do you think APP FT taking over is out of the question? I thought it can be useful under some special scenario such as an app wants to control its own FT but does not want to delete the Istio's policy. This can be quite a neat way to do.

@johnament Istio is an infrastructure. It does not make sense for Istio to implement any MP Ft apis. Besides, whether using MP FT is orthogonal to this issue. There still be a conflicting scenario.

**Comment by kenfinnigan** [comment]
@johnament, where are the details of what was come up with? I don't think it's appropriate for Istio to implement an MP API, as it doesn't cover application code, it's purely infrastructure as @Emily-Jiang says.

@Emily-Jiang, I just wasn't sure whether it made sense to allow an Application to "take over" from Istio. If Istio is present and configured for an environment then surely Ops don't want it subverted?

**Comment by Emily-Jiang** [comment]
@kenfinnigan I do agree in most case, app's FT should be switched off via #58 . I thought if we provide a way to switch off Istio per request, it might be useful. It covers the use case of using app FT together with Istio's fault handling. Since Timeout and Retries are conflicting, using this feature will create a kind of ecosystem (the conflict only occurs in the restful calls not accessing database etc). The other alternative will be switching off Retries and Timeout but we can not just pick the restful invocations.

**Comment by kenfinnigan** [comment]
I'm not seeing the use case where a microservice would be deployed in an environment that includes Istio and the microservice wants to overrule how Istio works.

We need to be careful before we start offering ways to overtake or disable external integrations, especially at the infrastructure level

**Comment by Emily-Jiang** [comment]
@kenfinnigan I understand your concern. In order to solve the conflicts of Timeout and Retry, we have a couple of ways:
1. disable Retry and Timeout in MP FT, which means all MP timeout and retries will be disabled (including the http requests and the ones that directly accessing database etc, which does not going through Istio).
2. Only target http requests that going through Istio. Disable either MP FT timeout and Retry. I think by the time we execute the user code and fire a http request, it will be too late to disable MP FT. The backup approach is to disable Istio's Retry and Timeout by resetting the two http headers, which at least solves the conflict. By the way, Ops can configure MP FT Retry and Timeout by setting the corresponding properties.

If 2 is not practical, maybe just doing 1 is sufficient.

**Comment by kenfinnigan** [comment]
I confess to not having had time to look at Istio in detail, so I can't comment on what the best approach for use with Istio might be.

However, I will mention that we don't want specific Istio behavior in MP FT. If we did then we'd need to incorporate appropriate handling for alternatives to Istio. If we do this, it needs to be in a way that Istio can be told to query something to know whether to disable itself, an environment property or the like.

**Comment by Emily-Jiang** [comment]
@kenfinnigan agreed! I am thinking of an environment property to switch off MP FT etc #58. Istio can easily disable its FT capability. Yes, Istio is just one of the use cases. Our solution must not just limit to Istio and not tightly link to Istio. 

This issue is just a fine-grained solution. If we think the fine-grained solution is not needed, just consider this issue as a way to potentially socialise app server providers on how best to cope with any infrastructure conflicts.

**Comment by hutchig** [comment]
Re "Ops can configure MP FT Retry and Timeout by setting the corresponding properties." do we want Annotations( parms ) to have an associated (but fixed?) ordinal? To enable override where not specified and override for all?

**Comment by Emily-Jiang** [comment]
@hutchig +1. In more details, the default value can have ordinal say 100, @Retry, the default value in the annotation of maxRetries have the ordinal of 100. When specifying @Retry(maxRetries=4), the maxRetries will have ordinal of 200. These properties can be overridden by external config sources e.g. system properties, which having the default ordinal of 400.  If defining a config source with ordinal of 150, they can overwrite the annotation default value maxRetries = 3 in @Retry but cannot override the specified value e.g. @Retry(maxRetries=4).

**Comment by hutchig** [comment]
Hi @Emily-Jiang, interesting...the difficulty in defining an ordinal 100 for the defaults (as opposed to just where values appear as parameters with ordinal 200 in the annotation) is that, because we do not expose the ordinal of a 'winning' ConfigSource from the ConfigService, the practical way (I can think of) to implement the scheme is to have a 'synthetic' ConfigSource, that the FaultTolerence implementation creates and which represents the FaultTolerence annotation values, and mix this in with default and discovered ConfigSources using the ConfigService. IF we take that as given - in order for the ConfigService to be able to implement some properties (e.g. ConfigSource.ordinal 150) overriding FT defaults and some not (e.g.  ConfigSource.ordinal 50) the synthetic FT annotations' ConfigSource would have to have properties representing all the defaults for all the business methods. I am not sure we really want that - because what is the use case of a Ops provided FT ConfigProperty of < 100 ordinal, it will never have any effect so it is not needed. So it is safe to say  that only FT ConfigProperties > 100 make sense - so we can safely so that any provided user/ops FT Property can override the default with no loss of function and the FT implementation ConfigSource need only provide properties for user specified parameters - which is likely to be a much much smaller set than all possible parameters for all business methods. That is why I only suggested that user provided values have an ordinal.

**Comment by Emily-Jiang** [comment]
I don't see any value of making default value special (not having any ordinal). If someone define a config source with a ordinal of 150, it can override the default. Later on, he can freely change the ordinal to 50 so that the default value will not be overriden.

**Comment by hutchig** [comment]
If you are happy having a FT ConfigSource with all the default parameters as method level properties in the implementation, or there is a better alternative way of implementing it - I will have a think, then it will work fine as you suggest, I am just chipping in from the implementation perspective.

**Comment by hutchig** [comment]
The other implementation head-scratcher is differentiating a user specified parameter that is equal to the default from a non-specified default using the annotation APIs. (from @tevans78)

**Comment by Emily-Jiang** [comment]
Since most traffic will go to Istio, there is little point to carry out the per request overwrite. close this issue for now.
