### ISSUE TITLE
Open Liberty 21.0.0.12-beta: MicroProfile Fault Tolerance 4.0 Compatible Certification Request

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-fault-tolerance#601]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  IBM
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Open Liberty 21.0.0.12-beta](https://github.com/OpenLiberty/open-liberty/releases/tag/gm-21.0.0.12-beta)
- [x] Specification Name, Version and download URL:<br/>
   MicroProfile Fault Tolerance 4.0
- [x] Public URL of TCK Results Summary:<br/>
  [MicroProfile Fault Tolerance 4.0 TCK result](https://openliberty.io/certifications/microprofile/5.0/faulttolerance/4.0/21.0.0.12-beta-TCKResults.html)
- [x] Java runtime used to run the implementation:<br/>
  Java 8 and Java 11
- [x] Any Additional Specification Certification Requirements:<br/>
  n/a
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  [Here](https://openliberty.io/certifications/microprofile/5.0/faulttolerance/4.0/21.0.0.12-beta-TCKResults.html)
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kwsutter** [comment]
Same comments as on the Config 3.0 CCR -- The specification reference on the TCK Results was a non-final version, and specific java product and version should be specified.  Nothing major.  Thanks!
