### ISSUE TITLE
Invalid jakarta.enterprise.util version

### ISSUE THREAD

**Issue by jGauravGupta** [eclipse/microprofile-fault-tolerance#603]
`jakarta.enterprise.util` version range defined in [bnd.bnd](https://github.com/eclipse/microprofile-fault-tolerance/blob/4.0/api/bnd.bnd#L4) is not correct.

Current version:
2.0,3

Expected version:
3.0,4

**Comment by Emily-Jiang** [comment]
We are not going to move to that version unnecessarily as we are not using any new APIs in the new version. I'm going to close this issue for now.
