### ISSUE TITLE
Unable to Set Circuit Breaker name at Runtime 

### ISSUE THREAD

**Issue by yogeshn** [eclipse/microprofile-fault-tolerance#615]
**Description**

As a:

- [X] API User (application developer)
- [ ] Specification Implementer

...I need to be able to:

I wanted to create a circuit breaker with a name that can be set at runtime. Is there a Builder which I use to set circuitbreaker name instead of using annotation?
```
@CircuitBreaker(requestVolumeThreshold = 4, failureRatio = 0.5, delay = 1000)
@CircuitBreakerName("#{hostUrl}")
public Uni<Response> get(HttpHeaders headers, String requestUri, URI hostUrl) throws Exception {
// Some logic
}
```

**Comment by Ladicek** [comment]
`@CircuitBreakerName` is a SmallRye Fault Tolerance specific feature which isn't present in the MicroProfile Fault Tolerance specification. Since an issue in SmallRye Fault Tolerance already [exists](https://github.com/smallrye/smallrye-fault-tolerance/issues/810), I'm closing this.
