### ISSUE TITLE
Add a programmatic API (i.e. built-in CDI beans to launch FT operation) to the spec

### ISSUE THREAD

**Issue by antoinesd** [eclipse/microprofile-fault-tolerance#63]
Right now, spec API is only driven thru annotation, it could bring some limitation since FT operation can only bound to a method.
User may like to launch different operations in the same method.
I'd like to introduce a built-in bean injected with `FaultToleranceController` interface allowing such usages.

**Comment by Emily-Jiang** [comment]
We talked about this. I think considering the timing for gearing up for September release. It might be good to add this in the next release. We have a lot of tcks to write and spec to finish off.

**Comment by Emily-Jiang** [comment]
Not going to pursue this.
