### ISSUE TITLE
Problem with metric types and units

### ISSUE THREAD

**Issue by donbourne** [eclipse/microprofile-fault-tolerance#639]
Apologies for the late issue, but I noticed problems with the FaultTolerance OpenTelemetry metrics spec (which I had previously looked at, but which I now realize was missing important criteria in my review).

The following MP FT metrics should switch from being OTel Gauges to being UpDownCounters (either `LongUpDownCounter` or `ObservableLongUpDownCounter`), the determining factor in choosing between Gauges and UpDownCounters is whether the metric in question is [addititve](https://opentelemetry.io/docs/specs/otel/metrics/supplementary-guidelines/#:~:text=If%20the%20measurement%20values%20are,increasing%20%2D%20use%20an%20Asynchronous%20UpDownCounter).  Looking at the metrics currently listed as using Gauges in the MP FT spec:
- `ft.bulkhead.executionsRunning` - this metric is additive (I can sum the value across all methods and the result would have meaning)
- `ft.bulkhead.executionsWaiting` - same. this seems additive.

I would also recommend that the `Histograms` be changed to `DoubleHistograms` with units of `(s)` (instead of nanoseconds).  Rationale is to match general guidance from prometheus to use seconds for durations, and precedent from [HTTP semantic convention](https://opentelemetry.io/docs/specs/semconv/http/http-metrics/) which times HTTP requests in seconds. This applies to:
- `ft.timeout.executionDuration`
- `ft.bulkhead.runningDuration`
- `ft.bulkhead.waitingDuration`

**Comment by Azquelt** [comment]
I think both of these make sense and I can see how we ended up here.

1. MP Metrics has neither an up-down counter or a Histogram that can process `double`
2. MP Metrics automatically converts to the standard units when outputting in prometheus format, so with that API using nanoseconds as the unit made sense
3. When we added support for Open Telemetry, we mostly did a like-for-like conversion of the metrics
    - We did catch that `ft.circuitbreaker.state.total` could now be an `ObservableLongCounter` rather than a `Gauge`, but I wasn't aware of the additive property being a difference between an up-down counter and a gauge.

**Comment by donbourne** [comment]
opened PR to address spec change #640

**Comment by donbourne** [comment]
For the OTel Histogram bucket boundaries, the [default boundaries](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#histogram-aggregations) are `[ 0, 5, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000 ]`.  I propose that we use the same bucket boundaries that are recommended for the [HTTP server request duration](https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration), which are `[ 0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10 ]`, keeping in mind those values would be in units of seconds.

**Comment by donbourne** [comment]
The histogram problem is the more serious of the two I mentioned. Currently the FT spec requires histograms with default bucket boundaries and units of nanoseconds with no mention of the required bucket boundaries. That implies times would be grouped into buckets with boundaries: `[ 0, 5, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000 ]` nanoseconds. That means almost anything timed would be put into the last "catch-all" histogram bucket since delays will generally be greater than 10000 nanoseconds (0.000001 seconds).

**Comment by Azquelt** [comment]
Oops, this was fixed by #640 and #641 but I forgot to close the issue.
